"""
Run once to populate the recipes table from the JS frontend data.
    python seed.py
"""
from database import SessionLocal, engine, Base
from models import Recipe, User
from sqlalchemy import text
import models  # register all models

Base.metadata.create_all(bind=engine)

RECIPES = [
    {
        "id": 0,
        "title": "Masala Dosa",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 320,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://images.unsplash.com/photo-1630383249896-483b1fbf7f9e?w=600&q=80",
        "pantry_match": 85,
        "ingredients": {"available": ["Rice", "Urad Dal", "Potato", "Mustard Seeds"], "missing": ["Curry Leaves"]},
        "nutrition": {"protein": 12, "carbs": 45, "fat": 8, "fiber": 6},
        "health_benefits": ["Good digestion", "Low fat", "Energy rich"],
        "steps": [
            "Prepare the dosa batter by soaking rice and urad dal overnight",
            "Grind the soaked ingredients into a smooth batter",
            "Ferment the batter for 8-12 hours",
            "Prepare the potato filling with boiled potatoes, onions, and spices",
            "Heat a griddle and pour a ladleful of batter",
            "Spread it thin in a circular motion",
            "Add oil around the edges and cook until crispy",
            "Place the potato filling in the center and fold",
            "Serve hot with coconut chutney and sambar",
        ],
        "cultural": "Masala Dosa is a traditional South Indian breakfast served with chutney and sambar.",
        "similar_dishes": ["Plain Dosa", "Uttapam", "Set Dosa"],
        "food_labels": ["dosa", "crepe", "pancake", "indian food", "breakfast", "rice crepe"],
    },
    {
        "id": 1,
        "title": "Paneer Butter Masala",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "45 minutes",
        "calories": 520,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&q=80",
        "pantry_match": 72,
        "ingredients": {"available": ["Paneer", "Butter", "Tomatoes", "Onion", "Spices"], "missing": ["Cream", "Kasuri Methi"]},
        "nutrition": {"protein": 18, "carbs": 35, "fat": 28, "fiber": 4},
        "health_benefits": ["High protein", "Calcium rich", "Bone health"],
        "steps": [
            "Cube the paneer and lightly fry until golden",
            "Blend tomatoes and onions into a smooth puree",
            "Heat butter and sauté spices until fragrant",
            "Add the tomato-onion puree and cook for 10 minutes",
            "Stir in cream and kasuri methi",
            "Add fried paneer cubes to the gravy",
            "Simmer for 5 minutes on low heat",
            "Garnish with fresh cream and serve hot",
        ],
        "cultural": "Paneer Butter Masala is a rich North Indian curry loved worldwide for its creamy tomato gravy.",
        "similar_dishes": ["Shahi Paneer", "Kadai Paneer", "Matar Paneer"],
        "food_labels": ["paneer", "curry", "indian food", "butter masala", "gravy", "cottage cheese"],
    },
    {
        "id": 2,
        "title": "Vegetable Stir Fry",
        "cuisine": "Asian",
        "diet": "Vegan",
        "time": "20 minutes",
        "calories": 250,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"], "missing": ["Sesame Oil"]},
        "nutrition": {"protein": 8, "carbs": 32, "fat": 10, "fiber": 7},
        "health_benefits": ["Low calorie", "High fiber", "Antioxidants"],
        "steps": [
            "Chop all vegetables into bite-sized pieces",
            "Heat oil in a wok over high heat",
            "Add garlic and stir fry for 30 seconds",
            "Add hard vegetables like broccoli first",
            "Toss in bell peppers and cook for 2 minutes",
            "Drizzle soy sauce and sesame oil, toss well",
        ],
        "cultural": "Stir frying originated in China and is one of the quickest, most nutritious cooking techniques.",
        "similar_dishes": ["Fried Rice", "Chow Mein", "Pad Thai"],
        "food_labels": ["stir fry", "vegetables", "broccoli", "asian food", "wok", "bell pepper"],
    },
    {
        "id": 3,
        "title": "Chicken Biryani",
        "cuisine": "Indian",
        "diet": "Non-Vegetarian",
        "time": "90 minutes",
        "calories": 650,
        "difficulty": "Hard",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80",
        "pantry_match": 75,
        "ingredients": {"available": ["Basmati Rice", "Chicken", "Onion", "Tomatoes", "Spices"], "missing": ["Saffron", "Kewra Water"]},
        "nutrition": {"protein": 35, "carbs": 60, "fat": 22, "fiber": 3},
        "health_benefits": ["High protein", "Energy rich", "Iron rich"],
        "steps": [
            "Marinate chicken with yogurt and spices for 2 hours",
            "Soak basmati rice for 30 minutes",
            "Fry onions until golden brown",
            "Cook marinated chicken until half done",
            "Parboil the rice with whole spices",
            "Layer rice and chicken in a heavy-bottomed pot",
            "Sprinkle saffron milk, fried onions and ghee",
            "Seal the pot and cook on dum (low heat) for 25 minutes",
            "Gently mix and serve with raita",
            "Garnish with boiled eggs and fresh coriander",
        ],
        "cultural": "Biryani traces its origins to Persia and was brought to India by the Mughals.",
        "similar_dishes": ["Pulao", "Dum Biryani", "Hyderabadi Biryani"],
        "food_labels": ["biryani", "rice", "chicken", "indian food", "fried rice", "spiced rice"],
    },
    {
        "id": 4,
        "title": "Greek Salad",
        "cuisine": "Western",
        "diet": "Vegetarian",
        "time": "15 minutes",
        "calories": 180,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Cucumber", "Tomatoes", "Olives", "Olive Oil"], "missing": ["Feta Cheese"]},
        "nutrition": {"protein": 6, "carbs": 15, "fat": 12, "fiber": 4},
        "health_benefits": ["Heart healthy", "Low carb", "Antioxidants"],
        "steps": [
            "Chop cucumber, tomatoes, and red onion into chunks",
            "Add Kalamata olives and crumbled feta cheese",
            "Drizzle generously with extra virgin olive oil",
            "Season with oregano, salt, and pepper and toss gently",
        ],
        "cultural": "Greek Salad, known as Horiatiki, is a staple of Mediterranean cuisine.",
        "similar_dishes": ["Caesar Salad", "Caprese Salad", "Fattoush"],
        "food_labels": ["salad", "greek salad", "vegetable salad", "feta", "olives", "mediterranean"],
    },
    {
        "id": 5,
        "title": "Chocolate Lava Cake",
        "cuisine": "Western",
        "diet": "Vegetarian",
        "time": "25 minutes",
        "calories": 450,
        "difficulty": "Medium",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Dark Chocolate", "Butter", "Eggs", "Sugar"], "missing": ["Heavy Cream"]},
        "nutrition": {"protein": 8, "carbs": 52, "fat": 24, "fiber": 3},
        "health_benefits": ["Mood booster", "Antioxidants", "Energy rich"],
        "steps": [
            "Preheat oven to 220°C and butter the ramekins",
            "Melt dark chocolate and butter together",
            "Whisk eggs, egg yolks, and sugar until pale",
            "Fold the chocolate mixture into the egg mixture",
            "Sift in flour and gently fold",
            "Pour batter into ramekins and refrigerate for 20 minutes",
            "Bake for exactly 12 minutes and invert onto plates",
        ],
        "cultural": "Chocolate Lava Cake was invented in New York in 1987 by chef Jean-Georges Vongerichten.",
        "similar_dishes": ["Chocolate Soufflé", "Brownie", "Chocolate Fondant"],
        "food_labels": ["chocolate cake", "lava cake", "dessert", "cake", "chocolate", "brownie"],
    },
    {
        "id": 6,
        "title": "Vegetable Spring Rolls",
        "cuisine": "Asian",
        "diet": "Vegan",
        "time": "35 minutes",
        "calories": 280,
        "difficulty": "Medium",
        "meal": "Snack",
        "image": "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=600&q=80",
        "pantry_match": 67,
        "ingredients": {"available": ["Cabbage", "Carrots", "Spring Roll Wrappers", "Soy Sauce"], "missing": ["Bean Sprouts", "Rice Noodles"]},
        "nutrition": {"protein": 7, "carbs": 38, "fat": 11, "fiber": 5},
        "health_benefits": ["Low calorie", "High fiber", "Vitamins"],
        "steps": [
            "Shred cabbage and julienne carrots",
            "Stir fry vegetables with soy sauce until tender",
            "Soak rice noodles and mix with vegetables",
            "Place filling on each spring roll wrapper",
            "Roll tightly, sealing edges with a flour paste",
            "Heat oil in a deep pan to 175°C",
            "Fry spring rolls until golden and crispy",
        ],
        "cultural": "Spring rolls originated in China and symbolize wealth and prosperity.",
        "similar_dishes": ["Egg Rolls", "Summer Rolls", "Lumpia"],
        "food_labels": ["spring roll", "egg roll", "fried roll", "asian food", "snack", "dumpling"],
    },
    {
        "id": 7,
        "title": "Quinoa Buddha Bowl",
        "cuisine": "Western",
        "diet": "Vegan",
        "time": "30 minutes",
        "calories": 380,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Quinoa", "Chickpeas", "Spinach", "Avocado"], "missing": ["Tahini"]},
        "nutrition": {"protein": 16, "carbs": 48, "fat": 14, "fiber": 10},
        "health_benefits": ["High protein", "High fiber", "Diabetic friendly"],
        "steps": [
            "Rinse and cook quinoa in vegetable broth for extra flavor",
            "Roast chickpeas with olive oil and spices at 200°C for 20 minutes",
            "Massage spinach with a pinch of salt and lemon juice",
            "Slice avocado and arrange all ingredients over quinoa",
            "Whisk tahini with lemon juice, garlic, and water for dressing",
            "Drizzle dressing over the bowl and serve",
        ],
        "cultural": "Buddha Bowls represent balanced, nourishing meals popularized in the global wellness food movement.",
        "similar_dishes": ["Poke Bowl", "Grain Bowl", "Açaí Bowl"],
        "food_labels": ["quinoa", "buddha bowl", "grain bowl", "salad bowl", "healthy bowl", "avocado bowl"],
    },
    {
        "id": 8,
        "title": "Beef Tacos",
        "cuisine": "Mexican",
        "diet": "Non-Vegetarian",
        "time": "25 minutes",
        "calories": 480,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
        "pantry_match": 78,
        "ingredients": {"available": ["Ground Beef", "Taco Shells", "Onion", "Garlic", "Cumin"], "missing": ["Salsa", "Sour Cream"]},
        "nutrition": {"protein": 28, "carbs": 30, "fat": 22, "fiber": 4},
        "health_benefits": ["High protein", "Iron rich", "Energy boost"],
        "steps": [
            "Brown ground beef in a skillet over medium-high heat",
            "Drain excess fat and add diced onion and garlic",
            "Season with cumin, chili powder, paprika, salt, and pepper",
            "Cook until beef is fully cooked and spices are fragrant",
            "Warm taco shells in the oven at 180°C for 3 minutes",
            "Fill shells with beef, shredded lettuce, and diced tomatoes",
            "Top with salsa, cheese, and a dollop of sour cream",
            "Serve immediately with lime wedges",
        ],
        "cultural": "Tacos are a traditional Mexican street food dating back centuries, now popular worldwide.",
        "similar_dishes": ["Burritos", "Quesadillas", "Nachos"],
        "food_labels": ["taco", "beef taco", "mexican food", "ground beef", "tortilla", "street food"],
    },
    {
        "id": 9,
        "title": "Margherita Pizza",
        "cuisine": "Italian",
        "diet": "Vegetarian",
        "time": "40 minutes",
        "calories": 560,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80",
        "pantry_match": 82,
        "ingredients": {"available": ["Pizza Dough", "Tomatoes", "Mozzarella", "Olive Oil", "Basil"], "missing": ["Semolina Flour"]},
        "nutrition": {"protein": 20, "carbs": 65, "fat": 18, "fiber": 3},
        "health_benefits": ["Calcium rich", "Lycopene from tomatoes", "Energy rich"],
        "steps": [
            "Preheat oven to 250°C with a pizza stone or baking tray inside",
            "Stretch pizza dough into a thin 30cm circle on a floured surface",
            "Spread crushed San Marzano tomatoes evenly over the base",
            "Season with salt, olive oil, and a pinch of oregano",
            "Tear fresh mozzarella and distribute evenly",
            "Slide pizza onto the hot stone and bake for 8-10 minutes",
            "Remove when crust is golden and slightly charred",
            "Top with fresh basil leaves and a drizzle of olive oil before serving",
        ],
        "cultural": "Margherita Pizza was created in 1889 in Naples, named after Queen Margherita of Italy.",
        "similar_dishes": ["Pepperoni Pizza", "Focaccia", "Calzone"],
        "food_labels": ["pizza", "margherita pizza", "italian food", "mozzarella", "tomato pizza", "flatbread"],
    },
    {
        "id": 10,
        "title": "Tom Yum Soup",
        "cuisine": "Thai",
        "diet": "Non-Vegetarian",
        "time": "30 minutes",
        "calories": 210,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
        "pantry_match": 65,
        "ingredients": {"available": ["Shrimp", "Mushrooms", "Lemongrass", "Lime Juice"], "missing": ["Galangal", "Kaffir Lime Leaves", "Nam Prik Pao"]},
        "nutrition": {"protein": 18, "carbs": 12, "fat": 6, "fiber": 2},
        "health_benefits": ["Immune boosting", "Low calorie", "Anti-inflammatory"],
        "steps": [
            "Bring chicken broth to a boil in a medium pot",
            "Add lemongrass (bruised), galangal slices, and kaffir lime leaves",
            "Simmer for 5 minutes to infuse the broth",
            "Add mushrooms and shrimp, cook for 3 minutes",
            "Stir in fish sauce, lime juice, and chili paste (Nam Prik Pao)",
            "Taste and adjust seasoning — it should be sour, salty, and spicy",
            "Ladle into bowls and garnish with fresh cilantro and chili slices",
        ],
        "cultural": "Tom Yum is Thailand's national soup, recognized as one of the world's most flavorful broths.",
        "similar_dishes": ["Tom Kha Gai", "Pho", "Hot and Sour Soup"],
        "food_labels": ["soup", "tom yum", "thai soup", "shrimp soup", "spicy soup", "asian soup"],
    },
    {
        "id": 11,
        "title": "Idli Sambar",
        "cuisine": "Indian",
        "diet": "Vegan",
        "time": "40 minutes",
        "calories": 290,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80",
        "pantry_match": 88,
        "ingredients": {"available": ["Idli Rice", "Urad Dal", "Toor Dal", "Tamarind", "Vegetables"], "missing": ["Sambar Powder"]},
        "nutrition": {"protein": 10, "carbs": 48, "fat": 4, "fiber": 8},
        "health_benefits": ["Probiotics from fermentation", "High fiber", "Low fat", "Good digestion"],
        "steps": [
            "Soak idli rice and urad dal separately for 6 hours",
            "Grind urad dal to a fluffy batter, then grind rice coarsely",
            "Combine batters with salt and ferment overnight",
            "Steam idlis in a greased idli mold for 10-12 minutes",
            "Pressure cook toor dal until soft",
            "Fry mustard seeds, curry leaves, and onions for the sambar base",
            "Add tamarind water, vegetables, and sambar powder",
            "Simmer with cooked dal for 15 minutes",
            "Serve hot idlis with sambar and coconut chutney",
        ],
        "cultural": "Idli Sambar is the quintessential South Indian breakfast enjoyed across Tamil Nadu and Karnataka.",
        "similar_dishes": ["Masala Dosa", "Uttapam", "Vada Sambar"],
        "food_labels": ["idli", "sambar", "south indian food", "steamed cake", "rice cake", "indian breakfast"],
    },
    {
        "id": 12,
        "title": "Spaghetti Carbonara",
        "cuisine": "Italian",
        "diet": "Non-Vegetarian",
        "time": "25 minutes",
        "calories": 620,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80",
        "pantry_match": 76,
        "ingredients": {"available": ["Spaghetti", "Eggs", "Parmesan", "Black Pepper"], "missing": ["Guanciale", "Pecorino Romano"]},
        "nutrition": {"protein": 26, "carbs": 68, "fat": 24, "fiber": 3},
        "health_benefits": ["High protein", "Calcium rich", "Energy rich"],
        "steps": [
            "Cook spaghetti in heavily salted boiling water until al dente",
            "Fry guanciale (or pancetta) in a pan until crispy, no oil needed",
            "Whisk eggs, grated Pecorino, grated Parmesan, and black pepper in a bowl",
            "Reserve 1 cup of starchy pasta cooking water",
            "Remove guanciale pan from heat, add drained spaghetti and toss",
            "Pour egg mixture over pasta and toss rapidly, adding pasta water little by little",
            "The heat from the pasta gently cooks the eggs into a creamy sauce",
            "Serve immediately with extra Pecorino and cracked black pepper",
        ],
        "cultural": "Carbonara originates from Rome and relies on the technique of emulsifying eggs without scrambling them.",
        "similar_dishes": ["Pasta Alfredo", "Cacio e Pepe", "Pasta Amatriciana"],
        "food_labels": ["pasta", "spaghetti", "carbonara", "italian pasta", "noodles", "creamy pasta"],
    },
    {
        "id": 13,
        "title": "Mango Lassi",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "10 minutes",
        "calories": 220,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80",
        "pantry_match": 90,
        "ingredients": {"available": ["Mango", "Yogurt", "Milk", "Sugar", "Cardamom"], "missing": []},
        "nutrition": {"protein": 6, "carbs": 40, "fat": 5, "fiber": 2},
        "health_benefits": ["Probiotic", "Vitamin C", "Bone health", "Cooling drink"],
        "steps": [
            "Peel and dice ripe Alphonso or Kesar mangoes",
            "Add mango pieces, thick yogurt, and cold milk to a blender",
            "Add sugar to taste and a pinch of cardamom powder",
            "Blend on high until completely smooth and frothy",
            "Taste and adjust sweetness or consistency with more milk",
            "Pour into chilled glasses over ice cubes",
            "Garnish with a mango slice and a sprinkle of cardamom",
        ],
        "cultural": "Mango Lassi is a beloved Indian beverage, especially popular during summer across North India.",
        "similar_dishes": ["Plain Lassi", "Strawberry Lassi", "Mango Shake"],
        "food_labels": ["lassi", "mango drink", "smoothie", "indian drink", "yogurt drink", "mango lassi"],
    },
    {
        "id": 14,
        "title": "Falafel Wrap",
        "cuisine": "Middle Eastern",
        "diet": "Vegan",
        "time": "35 minutes",
        "calories": 420,
        "difficulty": "Medium",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80",
        "pantry_match": 70,
        "ingredients": {"available": ["Chickpeas", "Parsley", "Cumin", "Pita Bread", "Tomato", "Lettuce"], "missing": ["Tahini", "Sumac"]},
        "nutrition": {"protein": 16, "carbs": 52, "fat": 14, "fiber": 9},
        "health_benefits": ["High fiber", "Plant protein", "Heart healthy", "Iron rich"],
        "steps": [
            "Soak dried chickpeas overnight — do NOT use canned",
            "Blend chickpeas with parsley, garlic, cumin, coriander, and salt into a coarse mixture",
            "Refrigerate mixture for 30 minutes, then form into small balls",
            "Deep fry falafels at 180°C until deep golden brown, about 3 minutes",
            "Mix tahini with lemon juice, garlic, and water into a smooth sauce",
            "Warm pita bread and spread tahini sauce on the inside",
            "Load with falafel, tomato, cucumber, lettuce, and pickled turnips",
            "Drizzle with extra tahini and wrap tightly",
        ],
        "cultural": "Falafel is a staple street food across Egypt, Lebanon, and Israel with thousands of years of history.",
        "similar_dishes": ["Hummus Pita", "Shawarma", "Sabich"],
        "food_labels": ["falafel", "wrap", "pita wrap", "middle eastern food", "chickpea fritter", "street food"],
    },
    {
        "id": 15,
        "title": "Banana Pancakes",
        "cuisine": "Western",
        "diet": "Vegetarian",
        "time": "20 minutes",
        "calories": 340,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&q=80",
        "pantry_match": 92,
        "ingredients": {"available": ["Banana", "Eggs", "Flour", "Milk", "Baking Powder", "Butter"], "missing": []},
        "nutrition": {"protein": 10, "carbs": 55, "fat": 10, "fiber": 4},
        "health_benefits": ["Energy rich", "Potassium boost", "Mood improvement", "Natural sugars"],
        "steps": [
            "Mash two ripe bananas in a large bowl until smooth",
            "Whisk in 2 eggs and 120ml milk",
            "Sift in 150g flour and 1 tsp baking powder, mix until just combined",
            "Do not overmix — a few lumps are fine",
            "Heat a non-stick pan over medium heat and add a small knob of butter",
            "Pour 3 tbsp of batter per pancake and cook until bubbles form on top",
            "Flip and cook for 1 more minute until golden",
            "Serve stacked with maple syrup, banana slices, and a dust of powdered sugar",
        ],
        "cultural": "Pancakes are enjoyed across cultures worldwide — this banana version is a modern healthy twist.",
        "similar_dishes": ["Regular Pancakes", "Waffles", "Crêpes"],
        "food_labels": ["pancake", "banana pancake", "breakfast", "crepe", "hotcake", "sweet pancake"],
    },
    {
        "id": 16,
        "title": "Dal Makhani",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "60 minutes",
        "calories": 430,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&q=80",
        "pantry_match": 74,
        "ingredients": {"available": ["Black Lentils", "Kidney Beans", "Butter", "Tomatoes", "Cream"], "missing": ["Kasuri Methi", "Charcoal for Dhungar"]},
        "nutrition": {"protein": 20, "carbs": 50, "fat": 16, "fiber": 14},
        "health_benefits": ["High protein", "High fiber", "Iron rich", "Heart healthy"],
        "steps": [
            "Soak black lentils (urad dal) and kidney beans overnight",
            "Pressure cook with water, salt, and a pinch of baking soda for 30 minutes",
            "In a separate pan, heat butter and sauté finely chopped onions until golden",
            "Add ginger-garlic paste and cook until raw smell disappears",
            "Stir in tomato puree, red chili powder, and garam masala",
            "Combine the cooked dal with the tomato gravy",
            "Simmer on low heat for 20-30 minutes, stirring occasionally",
            "Stir in fresh cream and kasuri methi",
            "Finish with a large knob of butter and serve with naan or rice",
        ],
        "cultural": "Dal Makhani was invented at Moti Mahal restaurant in Delhi in the 1950s by Kundan Lal Gujral.",
        "similar_dishes": ["Butter Chicken", "Rajma", "Dal Tadka"],
        "food_labels": ["dal", "lentil curry", "north indian food", "black dal", "indian curry", "dal makhani"],
    },
    {
        "id": 17,
        "title": "Avocado Toast",
        "cuisine": "Western",
        "diet": "Vegan",
        "time": "10 minutes",
        "calories": 280,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=600&q=80",
        "pantry_match": 95,
        "ingredients": {"available": ["Avocado", "Sourdough Bread", "Lemon", "Chili Flakes", "Salt", "Olive Oil"], "missing": []},
        "nutrition": {"protein": 7, "carbs": 28, "fat": 16, "fiber": 8},
        "health_benefits": ["Heart healthy fats", "High fiber", "Potassium rich", "Anti-inflammatory"],
        "steps": [
            "Toast sourdough bread slices to your preferred crunchiness",
            "Halve the avocado, remove the pit, and scoop flesh into a bowl",
            "Mash avocado with a fork, add lemon juice, salt, and black pepper",
            "For chunky — mash lightly; for smooth — mash thoroughly",
            "Spread generously over the warm toast",
            "Sprinkle chili flakes, everything bagel seasoning, or microgreens",
            "Drizzle a small amount of good quality olive oil on top",
            "Optional: top with a poached egg for extra protein",
        ],
        "cultural": "Avocado Toast became a global brunch phenomenon in the 2010s, originating from Australian café culture.",
        "similar_dishes": ["Bruschetta", "Egg Toast", "Shakshuka"],
        "food_labels": ["avocado toast", "toast", "avocado", "breakfast toast", "brunch", "sourdough toast"],
    },
    {
        "id": 18,
        "title": "Payasam",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "35 minutes",
        "calories": 310,
        "difficulty": "Easy",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1625398407796-82da8a8b3b7e?w=600&q=80",
        "pantry_match": 88,
        "ingredients": {"available": ["Milk", "Rice", "Sugar", "Cardamom", "Cashews", "Raisins"], "missing": ["Saffron"]},
        "nutrition": {"protein": 7, "carbs": 55, "fat": 9, "fiber": 1},
        "health_benefits": ["Calcium rich", "Energy boost", "Mood booster", "Bone health"],
        "steps": [
            "Wash rice and soak for 15 minutes, then drain",
            "Bring full-fat milk to a boil in a heavy-bottomed pan",
            "Add soaked rice and stir continuously on medium heat",
            "Cook for 20-25 minutes until rice is completely soft and milk thickens",
            "Add sugar and stir until fully dissolved",
            "Mix in cardamom powder and a few strands of saffron soaked in warm milk",
            "In a small pan, fry cashews and raisins in ghee until golden",
            "Pour the fried cashews and raisins over the payasam",
            "Serve warm or chilled — both ways are delicious",
        ],
        "cultural": "Payasam (Kheer) is an ancient Indian dessert mentioned in the Mahabharata, prepared during festivals and celebrations.",
        "similar_dishes": ["Kheer", "Firni", "Rice Pudding"],
        "food_labels": ["payasam", "kheer", "rice pudding", "indian dessert", "sweet porridge", "milk dessert"],
    },
    {
        "id": 19,
        "title": "Gulab Jamun",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "45 minutes",
        "calories": 380,
        "difficulty": "Medium",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1666608601842-d4b216c3f7f7?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Milk Powder", "Flour", "Ghee", "Sugar", "Cardamom"], "missing": ["Khoya", "Rose Water"]},
        "nutrition": {"protein": 5, "carbs": 60, "fat": 14, "fiber": 1},
        "health_benefits": ["Instant energy", "Mood booster", "Good for celebrations"],
        "steps": [
            "Mix milk powder, a little flour, a pinch of baking soda, and ghee into a soft dough",
            "Add just enough milk to bind — dough should be soft but not sticky",
            "Rest the dough for 10 minutes covered with a damp cloth",
            "Prepare sugar syrup: dissolve 2 cups sugar in 1 cup water, add cardamom and rose water",
            "Simmer syrup for 5 minutes and keep warm",
            "Roll dough into smooth balls with no cracks — about marble size",
            "Deep fry the balls in ghee or oil on low heat, stirring gently for even browning",
            "Fry until deep golden brown — this takes about 8-10 minutes",
            "Transfer hot gulab jamuns directly into warm sugar syrup",
            "Soak for at least 2 hours before serving — they will double in size",
        ],
        "cultural": "Gulab Jamun is derived from a Persian dish and has been enjoyed across India for over 500 years.",
        "similar_dishes": ["Rasgulla", "Jamun", "Pantua"],
        "food_labels": ["gulab jamun", "indian sweet", "sweet ball", "fried sweet", "dessert", "mithai"],
    },
    {
        "id": 20,
        "title": "Rasgulla",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "50 minutes",
        "calories": 180,
        "difficulty": "Hard",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80",
        "pantry_match": 75,
        "ingredients": {"available": ["Full-fat Milk", "Lemon Juice", "Sugar", "Water"], "missing": ["Rose Water"]},
        "nutrition": {"protein": 6, "carbs": 30, "fat": 4, "fiber": 0},
        "health_benefits": ["Calcium rich", "Low fat dessert", "Protein source"],
        "steps": [
            "Boil full-fat milk, then add lemon juice to curdle it",
            "Strain the chenna (paneer curd) through a muslin cloth",
            "Wash the chenna under cold water to remove lemon sourness",
            "Squeeze out excess water — chenna should be moist but not wet",
            "Knead chenna for 8-10 minutes until smooth and soft like dough",
            "Roll into small smooth balls with no cracks",
            "Boil sugar and water into a light syrup in a wide pot",
            "Drop chenna balls into boiling syrup, cover and cook for 15 minutes on medium heat",
            "Balls will double in size — do not open the lid during cooking",
            "Let cool, add rose water, and refrigerate before serving",
        ],
        "cultural": "Rasgulla originated in Odisha and Bengal and is now one of India's most iconic desserts, with a geographical indication tag.",
        "similar_dishes": ["Rasmalai", "Cham Cham", "Gulab Jamun"],
        "food_labels": ["rasgulla", "indian sweet", "chhena sweet", "syrup sweet", "bengali sweet", "mithai"],
    },
    {
        "id": 21,
        "title": "Halwa",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 420,
        "difficulty": "Easy",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1666608601938-9b46c7b4e7b4?w=600&q=80",
        "pantry_match": 85,
        "ingredients": {"available": ["Semolina", "Sugar", "Ghee", "Water", "Cardamom", "Cashews"], "missing": ["Saffron"]},
        "nutrition": {"protein": 5, "carbs": 65, "fat": 16, "fiber": 2},
        "health_benefits": ["Quick energy", "Warming food", "Iron from semolina"],
        "steps": [
            "Heat ghee in a heavy pan over medium flame",
            "Add cashews and fry until golden, then set aside",
            "Add semolina (rava) to the same ghee and roast on low heat",
            "Stir continuously until semolina turns golden and smells nutty — about 8 minutes",
            "Carefully pour in hot water (2 cups per 1 cup semolina) — it will splutter",
            "Stir quickly to prevent lumps from forming",
            "Add sugar and mix well until fully combined",
            "Cook on low heat, stirring until halwa leaves the sides of the pan",
            "Mix in cardamom powder and saffron milk",
            "Garnish with fried cashews and serve hot",
        ],
        "cultural": "Sooji Halwa is a sacred offering (prasad) in Hindu temples and is served at weddings and festivals across India.",
        "similar_dishes": ["Gajar Halwa", "Moong Dal Halwa", "Sheera"],
        "food_labels": ["halwa", "sooji halwa", "semolina dessert", "indian sweet", "sheera", "rava halwa"],
    },
    {
        "id": 22,
        "title": "Pani Puri",
        "cuisine": "Indian",
        "diet": "Vegan",
        "time": "30 minutes",
        "calories": 200,
        "difficulty": "Medium",
        "meal": "Snack",
        "image": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&q=80",
        "pantry_match": 70,
        "ingredients": {"available": ["Semolina", "Boiled Potatoes", "Chickpeas", "Tamarind", "Mint"], "missing": ["Puri", "Black Salt"]},
        "nutrition": {"protein": 5, "carbs": 38, "fat": 6, "fiber": 5},
        "health_benefits": ["Low calorie snack", "Digestive boost from mint", "Probiotic from tamarind"],
        "steps": [
            "Mix semolina and a little flour with water into a stiff dough and rest for 20 minutes",
            "Roll very thin and cut into small circles",
            "Deep fry on medium heat, pressing gently so they puff up",
            "Drain and cool on paper towels",
            "Boil and mash potatoes with boiled chickpeas, chaat masala, and tamarind chutney",
            "Blend mint, coriander, green chili, ginger, lemon juice, and black salt for green water",
            "Make sweet water with tamarind pulp, jaggery, cumin, and black salt",
            "Just before serving, make a hole in each puri with your thumb",
            "Fill with potato mixture and dip into spicy or sweet water",
            "Eat immediately in one gulp!",
        ],
        "cultural": "Pani Puri is India's most beloved street food, known as Golgappa in the North and Phuchka in Bengal.",
        "similar_dishes": ["Bhel Puri", "Sev Puri", "Dahi Puri"],
        "food_labels": ["pani puri", "golgappa", "phuchka", "indian street food", "chaat", "crispy puri"],
    },
    {
        "id": 23,
        "title": "Butter Chicken",
        "cuisine": "North Indian",
        "diet": "Non-Vegetarian",
        "time": "50 minutes",
        "calories": 580,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80",
        "pantry_match": 76,
        "ingredients": {"available": ["Chicken", "Butter", "Tomatoes", "Onion", "Cream", "Spices"], "missing": ["Kasuri Methi", "Tandoor Paste"]},
        "nutrition": {"protein": 34, "carbs": 20, "fat": 32, "fiber": 3},
        "health_benefits": ["High protein", "Vitamin A from tomatoes", "Immune boosting"],
        "steps": [
            "Marinate chicken in yogurt, ginger-garlic paste, and spices for at least 2 hours",
            "Grill or pan-fry marinated chicken until slightly charred",
            "In the same pan, melt butter and fry onions until golden",
            "Add ginger-garlic paste and cook until fragrant",
            "Blend in tomato puree and cook for 15 minutes until oil separates",
            "Add red chili powder, coriander powder, and garam masala",
            "Add the grilled chicken to the sauce and simmer for 10 minutes",
            "Stir in fresh cream and crushed kasuri methi",
            "Finish with a generous knob of cold butter swirled in at the end",
            "Serve with naan or steamed basmati rice",
        ],
        "cultural": "Butter Chicken (Murgh Makhani) was accidentally invented at Moti Mahal in Delhi in the 1950s.",
        "similar_dishes": ["Chicken Tikka Masala", "Dal Makhani", "Paneer Butter Masala"],
        "food_labels": ["butter chicken", "murgh makhani", "chicken curry", "indian chicken", "creamy curry", "north indian food"],
    },
    {
        "id": 24,
        "title": "Jalebi",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "60 minutes",
        "calories": 350,
        "difficulty": "Hard",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1601050690117-94f5f7b8fefe?w=600&q=80",
        "pantry_match": 72,
        "ingredients": {"available": ["Flour", "Yogurt", "Sugar", "Saffron", "Ghee"], "missing": ["Yeast", "Rose Water", "Piping Bag"]},
        "nutrition": {"protein": 3, "carbs": 65, "fat": 14, "fiber": 1},
        "health_benefits": ["Quick energy", "Mood booster", "Iron from saffron"],
        "steps": [
            "Mix flour, yogurt, a pinch of turmeric, and yeast with water into a smooth thin batter",
            "Let the batter ferment for 8-12 hours at room temperature",
            "Prepare sugar syrup: boil sugar and water with saffron and cardamom to one-string consistency",
            "Keep syrup warm on very low heat",
            "Fill a squeeze bottle or piping bag with the fermented batter",
            "Heat ghee or oil in a wide shallow pan",
            "Pipe concentric circles quickly into the hot oil to form jalebi shapes",
            "Fry on medium heat until golden and crispy on both sides",
            "Transfer immediately to warm sugar syrup and soak for 1-2 minutes",
            "Serve hot — the contrast of crispy outside and syrup inside is key",
        ],
        "cultural": "Jalebi is believed to have Persian origins (Zulbia) and has been a part of Indian festivals for centuries.",
        "similar_dishes": ["Imarti", "Funnel Cake", "Gulab Jamun"],
        "food_labels": ["jalebi", "indian sweet", "fried sweet", "coil sweet", "syrup sweet", "festival sweet"],
    },
    {
        "id": 25,
        "title": "Chole Bhature",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "45 minutes",
        "calories": 680,
        "difficulty": "Medium",
        "meal": "Breakfast",
        "image": "https://images.unsplash.com/photo-1626776876729-bab4369a5a5a?w=600&q=80",
        "pantry_match": 72,
        "ingredients": {"available": ["Chickpeas", "Flour", "Onion", "Tomatoes", "Spices", "Oil"], "missing": ["Anardana (Pomegranate Powder)", "Kashmiri Red Chili"]},
        "nutrition": {"protein": 18, "carbs": 82, "fat": 26, "fiber": 12},
        "health_benefits": ["High protein", "High fiber", "Iron rich", "Plant-based protein"],
        "steps": [
            "Soak chickpeas overnight and pressure cook with tea bags (for dark color)",
            "Prepare the chole masala: fry onions, add tomatoes and all spices",
            "Mix in cooked chickpeas and simmer for 20 minutes",
            "Mash a few chickpeas against the pot to thicken the gravy",
            "For bhature: knead maida (flour) with yogurt, oil, salt into a soft dough",
            "Rest dough for 2 hours for the yogurt to activate",
            "Roll into oval discs about 5mm thick",
            "Deep fry in hot oil — the bhatura will puff up dramatically",
            "Drain and serve immediately with the hot chole",
            "Garnish with raw onion rings, green chili, and lemon wedge",
        ],
        "cultural": "Chole Bhature is a popular Punjabi breakfast and is a staple street food from Delhi's Chandni Chowk.",
        "similar_dishes": ["Chole Puri", "Rajma Chawal", "Dal Makhani"],
        "food_labels": ["chole bhature", "chickpea curry", "fried bread", "north indian food", "punjabi food", "street food"],
    },
    {
        "id": 26,
        "title": "Tiramisu",
        "cuisine": "Italian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 430,
        "difficulty": "Medium",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80",
        "pantry_match": 74,
        "ingredients": {"available": ["Eggs", "Sugar", "Coffee", "Cocoa Powder"], "missing": ["Mascarpone Cheese", "Ladyfinger Biscuits", "Rum"]},
        "nutrition": {"protein": 8, "carbs": 42, "fat": 22, "fiber": 1},
        "health_benefits": ["Mood booster", "Antioxidants from coffee and cocoa", "Energy rich"],
        "steps": [
            "Separate egg yolks and whites into two clean bowls",
            "Whisk yolks with sugar until pale, thick, and doubled in volume",
            "Fold mascarpone cheese into the yolk mixture until smooth",
            "Beat egg whites to stiff peaks and gently fold into the mascarpone mixture",
            "Brew strong espresso and mix with a splash of rum or coffee liqueur, let cool",
            "Quickly dip ladyfinger biscuits one by one into the coffee mixture — 1 second per side",
            "Lay a layer of soaked ladyfingers in a deep dish",
            "Spread half the mascarpone cream over the biscuits",
            "Repeat with another layer of ladyfingers and remaining cream",
            "Dust generously with cocoa powder, refrigerate for at least 4 hours before serving",
        ],
        "cultural": "Tiramisu means 'pick me up' in Italian and originated in Treviso, Italy in the late 1960s.",
        "similar_dishes": ["Panna Cotta", "Charlotte Royale", "Chocolate Mousse"],
        "food_labels": ["tiramisu", "italian dessert", "coffee dessert", "mascarpone dessert", "no bake dessert", "layered dessert"],
    },
    {
        "id": 27,
        "title": "Aloo Paratha",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 410,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://images.unsplash.com/photo-1615361200141-f45040f367be?w=600&q=80",
        "pantry_match": 90,
        "ingredients": {"available": ["Whole Wheat Flour", "Potatoes", "Onion", "Green Chili", "Spices", "Ghee"], "missing": []},
        "nutrition": {"protein": 9, "carbs": 60, "fat": 14, "fiber": 6},
        "health_benefits": ["High fiber", "Energy rich", "Good for digestion", "Iron from whole wheat"],
        "steps": [
            "Knead whole wheat flour with water and a pinch of salt into a soft smooth dough",
            "Rest dough covered for 20 minutes",
            "Boil potatoes until tender, peel and mash completely while hot",
            "Mix mashed potato with finely chopped onion, green chili, cumin seeds, and coriander",
            "Season with chaat masala, amchur (dry mango powder), and salt",
            "Divide dough into balls, flatten slightly, place a ball of filling in the center",
            "Gather dough edges around the filling and seal into a stuffed ball",
            "Gently roll out into a thick flatbread, being careful not to burst the filling",
            "Cook on a hot tawa (griddle) with generous ghee on both sides until golden spots appear",
            "Serve piping hot with yogurt, pickle, and white butter",
        ],
        "cultural": "Aloo Paratha is the pride of Punjabi breakfasts and is iconic at the dhabas (roadside eateries) of Amritsar.",
        "similar_dishes": ["Plain Paratha", "Gobhi Paratha", "Mooli Paratha"],
        "food_labels": ["paratha", "aloo paratha", "stuffed flatbread", "north indian breakfast", "punjabi food", "flatbread"],
    },
]


def seed():
    db = SessionLocal()
    try:
        existing_ids = {r.id for r in db.query(Recipe.id).all()}
        new_recipes = [r for r in RECIPES if r["id"] not in existing_ids]

        if not new_recipes:
            # Still fix the sequence even if no new recipes to add
            db.execute(text("SELECT setval('recipes_id_seq', (SELECT MAX(id) FROM recipes) + 1, false)"))
            db.commit()
            print(f"All {len(RECIPES)} recipes already exist. Sequence reset to {len(existing_ids) + 1}.")
            return

        for data in new_recipes:
            recipe = Recipe(**data)
            db.add(recipe)

        db.commit()

        # Reset the PostgreSQL sequence so future auto-increment IDs don't collide
        # with the manually-seeded IDs (0–27)
        db.execute(text("SELECT setval('recipes_id_seq', (SELECT MAX(id) FROM recipes) + 1, false)"))
        db.commit()

        total = len(existing_ids) + len(new_recipes)
        print(f"✅ Seeded {len(new_recipes)} new recipes. Total in DB: {total}")
        print(f"✅ PostgreSQL sequence reset to {total + 1}")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
