"""
Run once to populate the recipes table from the JS frontend data.
    python seed.py
"""
from database import SessionLocal, engine, Base
from models import Recipe, User
from sqlalchemy import text
import models  # register all models

Base.metadata.create_all(bind=engine)

RECIPES = [
    {
        "id": 0,
        "title": "Masala Dosa",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 320,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Rameshwaram_Cafe_Dosa.jpg/330px-Rameshwaram_Cafe_Dosa.jpg",
        "pantry_match": 85,
        "ingredients": {"available": ["Rice", "Urad Dal", "Potato", "Mustard Seeds"], "missing": ["Curry Leaves"]},
        "nutrition": {"protein": 12, "carbs": 45, "fat": 8, "fiber": 6},
        "health_benefits": ["Good digestion", "Low fat", "Energy rich"],
        "steps": [
            "Prepare the dosa batter by soaking rice and urad dal overnight",
            "Grind the soaked ingredients into a smooth batter",
            "Ferment the batter for 8-12 hours",
            "Prepare the potato filling with boiled potatoes, onions, and spices",
            "Heat a griddle and pour a ladleful of batter",
            "Spread it thin in a circular motion",
            "Add oil around the edges and cook until crispy",
            "Place the potato filling in the center and fold",
            "Serve hot with coconut chutney and sambar",
        ],
        "cultural": "Masala Dosa is a traditional South Indian breakfast served with chutney and sambar.",
        "similar_dishes": ["Plain Dosa", "Uttapam", "Set Dosa"],
        "food_labels": ["dosa", "crepe", "pancake", "indian food", "breakfast", "rice crepe"],
    },
    {
        "id": 1,
        "title": "Paneer Butter Masala",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "45 minutes",
        "calories": 520,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Shahi_panner.jpg/330px-Shahi_panner.jpg",
        "pantry_match": 72,
        "ingredients": {"available": ["Paneer", "Butter", "Tomatoes", "Onion", "Spices"], "missing": ["Cream", "Kasuri Methi"]},
        "nutrition": {"protein": 18, "carbs": 35, "fat": 28, "fiber": 4},
        "health_benefits": ["High protein", "Calcium rich", "Bone health"],
        "steps": [
            "Cube the paneer and lightly fry until golden",
            "Blend tomatoes and onions into a smooth puree",
            "Heat butter and sauté spices until fragrant",
            "Add the tomato-onion puree and cook for 10 minutes",
            "Stir in cream and kasuri methi",
            "Add fried paneer cubes to the gravy",
            "Simmer for 5 minutes on low heat",
            "Garnish with fresh cream and serve hot",
        ],
        "cultural": "Paneer Butter Masala is a rich North Indian curry loved worldwide for its creamy tomato gravy.",
        "similar_dishes": ["Shahi Paneer", "Kadai Paneer", "Matar Paneer"],
        "food_labels": ["paneer", "curry", "indian food", "butter masala", "gravy", "cottage cheese"],
    },
    {
        "id": 2,
        "title": "Vegetable Stir Fry",
        "cuisine": "Asian",
        "diet": "Vegan",
        "time": "20 minutes",
        "calories": 250,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"], "missing": ["Sesame Oil"]},
        "nutrition": {"protein": 8, "carbs": 32, "fat": 10, "fiber": 7},
        "health_benefits": ["Low calorie", "High fiber", "Antioxidants"],
        "steps": [
            "Chop all vegetables into bite-sized pieces",
            "Heat oil in a wok over high heat",
            "Add garlic and stir fry for 30 seconds",
            "Add hard vegetables like broccoli first",
            "Toss in bell peppers and cook for 2 minutes",
            "Drizzle soy sauce and sesame oil, toss well",
        ],
        "cultural": "Stir frying originated in China and is one of the quickest, most nutritious cooking techniques.",
        "similar_dishes": ["Fried Rice", "Chow Mein", "Pad Thai"],
        "food_labels": ["stir fry", "vegetables", "broccoli", "asian food", "wok", "bell pepper"],
    },
    {
        "id": 3,
        "title": "Chicken Biryani",
        "cuisine": "Indian",
        "diet": "Non-Vegetarian",
        "time": "90 minutes",
        "calories": 650,
        "difficulty": "Hard",
        "meal": "Lunch",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg/330px-%22Hyderabadi_Dum_Biryani%22.jpg",
        "pantry_match": 75,
        "ingredients": {"available": ["Basmati Rice", "Chicken", "Onion", "Tomatoes", "Spices"], "missing": ["Saffron", "Kewra Water"]},
        "nutrition": {"protein": 35, "carbs": 60, "fat": 22, "fiber": 3},
        "health_benefits": ["High protein", "Energy rich", "Iron rich"],
        "steps": [
            "Marinate chicken with yogurt and spices for 2 hours",
            "Soak basmati rice for 30 minutes",
            "Fry onions until golden brown",
            "Cook marinated chicken until half done",
            "Parboil the rice with whole spices",
            "Layer rice and chicken in a heavy-bottomed pot",
            "Sprinkle saffron milk, fried onions and ghee",
            "Seal the pot and cook on dum (low heat) for 25 minutes",
            "Gently mix and serve with raita",
            "Garnish with boiled eggs and fresh coriander",
        ],
        "cultural": "Biryani traces its origins to Persia and was brought to India by the Mughals.",
        "similar_dishes": ["Pulao", "Dum Biryani", "Hyderabadi Biryani"],
        "food_labels": ["biryani", "rice", "chicken", "indian food", "fried rice", "spiced rice"],
    },
    {
        "id": 4,
        "title": "Greek Salad",
        "cuisine": "Western",
        "diet": "Vegetarian",
        "time": "15 minutes",
        "calories": 180,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Cucumber", "Tomatoes", "Olives", "Olive Oil"], "missing": ["Feta Cheese"]},
        "nutrition": {"protein": 6, "carbs": 15, "fat": 12, "fiber": 4},
        "health_benefits": ["Heart healthy", "Low carb", "Antioxidants"],
        "steps": [
            "Chop cucumber, tomatoes, and red onion into chunks",
            "Add Kalamata olives and crumbled feta cheese",
            "Drizzle generously with extra virgin olive oil",
            "Season with oregano, salt, and pepper and toss gently",
        ],
        "cultural": "Greek Salad, known as Horiatiki, is a staple of Mediterranean cuisine.",
        "similar_dishes": ["Caesar Salad", "Caprese Salad", "Fattoush"],
        "food_labels": ["salad", "greek salad", "vegetable salad", "feta", "olives", "mediterranean"],
    },
    {
        "id": 5,
        "title": "Chocolate Lava Cake",
        "cuisine": "Western",
        "diet": "Vegetarian",
        "time": "25 minutes",
        "calories": 450,
        "difficulty": "Medium",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Dark Chocolate", "Butter", "Eggs", "Sugar"], "missing": ["Heavy Cream"]},
        "nutrition": {"protein": 8, "carbs": 52, "fat": 24, "fiber": 3},
        "health_benefits": ["Mood booster", "Antioxidants", "Energy rich"],
        "steps": [
            "Preheat oven to 220°C and butter the ramekins",
            "Melt dark chocolate and butter together",
            "Whisk eggs, egg yolks, and sugar until pale",
            "Fold the chocolate mixture into the egg mixture",
            "Sift in flour and gently fold",
            "Pour batter into ramekins and refrigerate for 20 minutes",
            "Bake for exactly 12 minutes and invert onto plates",
        ],
        "cultural": "Chocolate Lava Cake was invented in New York in 1987 by chef Jean-Georges Vongerichten.",
        "similar_dishes": ["Chocolate Soufflé", "Brownie", "Chocolate Fondant"],
        "food_labels": ["chocolate cake", "lava cake", "dessert", "cake", "chocolate", "brownie"],
    },
    {
        "id": 6,
        "title": "Vegetable Spring Rolls",
        "cuisine": "Asian",
        "diet": "Vegan",
        "time": "35 minutes",
        "calories": 280,
        "difficulty": "Medium",
        "meal": "Snack",
        "image": "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=600&q=80",
        "pantry_match": 67,
        "ingredients": {"available": ["Cabbage", "Carrots", "Spring Roll Wrappers", "Soy Sauce"], "missing": ["Bean Sprouts", "Rice Noodles"]},
        "nutrition": {"protein": 7, "carbs": 38, "fat": 11, "fiber": 5},
        "health_benefits": ["Low calorie", "High fiber", "Vitamins"],
        "steps": [
            "Shred cabbage and julienne carrots",
            "Stir fry vegetables with soy sauce until tender",
            "Soak rice noodles and mix with vegetables",
            "Place filling on each spring roll wrapper",
            "Roll tightly, sealing edges with a flour paste",
            "Heat oil in a deep pan to 175°C",
            "Fry spring rolls until golden and crispy",
        ],
        "cultural": "Spring rolls originated in China and symbolize wealth and prosperity.",
        "similar_dishes": ["Egg Rolls", "Summer Rolls", "Lumpia"],
        "food_labels": ["spring roll", "egg roll", "fried roll", "asian food", "snack", "dumpling"],
    },
    {
        "id": 7,
        "title": "Quinoa Buddha Bowl",
        "cuisine": "Western",
        "diet": "Vegan",
        "time": "30 minutes",
        "calories": 380,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
        "pantry_match": 80,
        "ingredients": {"available": ["Quinoa", "Chickpeas", "Spinach", "Avocado"], "missing": ["Tahini"]},
        "nutrition": {"protein": 16, "carbs": 48, "fat": 14, "fiber": 10},
        "health_benefits": ["High protein", "High fiber", "Diabetic friendly"],
        "steps": [
            "Rinse and cook quinoa in vegetable broth for extra flavor",
            "Roast chickpeas with olive oil and spices at 200°C for 20 minutes",
            "Massage spinach with a pinch of salt and lemon juice",
            "Slice avocado and arrange all ingredients over quinoa",
            "Whisk tahini with lemon juice, garlic, and water for dressing",
            "Drizzle dressing over the bowl and serve",
        ],
        "cultural": "Buddha Bowls represent balanced, nourishing meals popularized in the global wellness food movement.",
        "similar_dishes": ["Poke Bowl", "Grain Bowl", "Açaí Bowl"],
        "food_labels": ["quinoa", "buddha bowl", "grain bowl", "salad bowl", "healthy bowl", "avocado bowl"],
    },
    {
        "id": 8,
        "title": "Beef Tacos",
        "cuisine": "Mexican",
        "diet": "Non-Vegetarian",
        "time": "25 minutes",
        "calories": 480,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
        "pantry_match": 78,
        "ingredients": {"available": ["Ground Beef", "Taco Shells", "Onion", "Garlic", "Cumin"], "missing": ["Salsa", "Sour Cream"]},
        "nutrition": {"protein": 28, "carbs": 30, "fat": 22, "fiber": 4},
        "health_benefits": ["High protein", "Iron rich", "Energy boost"],
        "steps": [
            "Brown ground beef in a skillet over medium-high heat",
            "Drain excess fat and add diced onion and garlic",
            "Season with cumin, chili powder, paprika, salt, and pepper",
            "Cook until beef is fully cooked and spices are fragrant",
            "Warm taco shells in the oven at 180°C for 3 minutes",
            "Fill shells with beef, shredded lettuce, and diced tomatoes",
            "Top with salsa, cheese, and a dollop of sour cream",
            "Serve immediately with lime wedges",
        ],
        "cultural": "Tacos are a traditional Mexican street food dating back centuries, now popular worldwide.",
        "similar_dishes": ["Burritos", "Quesadillas", "Nachos"],
        "food_labels": ["taco", "beef taco", "mexican food", "ground beef", "tortilla", "street food"],
    },
    {
        "id": 9,
        "title": "Margherita Pizza",
        "cuisine": "Italian",
        "diet": "Vegetarian",
        "time": "40 minutes",
        "calories": 560,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80",
        "pantry_match": 82,
        "ingredients": {"available": ["Pizza Dough", "Tomatoes", "Mozzarella", "Olive Oil", "Basil"], "missing": ["Semolina Flour"]},
        "nutrition": {"protein": 20, "carbs": 65, "fat": 18, "fiber": 3},
        "health_benefits": ["Calcium rich", "Lycopene from tomatoes", "Energy rich"],
        "steps": [
            "Preheat oven to 250°C with a pizza stone or baking tray inside",
            "Stretch pizza dough into a thin 30cm circle on a floured surface",
            "Spread crushed San Marzano tomatoes evenly over the base",
            "Season with salt, olive oil, and a pinch of oregano",
            "Tear fresh mozzarella and distribute evenly",
            "Slide pizza onto the hot stone and bake for 8-10 minutes",
            "Remove when crust is golden and slightly charred",
            "Top with fresh basil leaves and a drizzle of olive oil before serving",
        ],
        "cultural": "Margherita Pizza was created in 1889 in Naples, named after Queen Margherita of Italy.",
        "similar_dishes": ["Pepperoni Pizza", "Focaccia", "Calzone"],
        "food_labels": ["pizza", "margherita pizza", "italian food", "mozzarella", "tomato pizza", "flatbread"],
    },
    {
        "id": 10,
        "title": "Tom Yum Soup",
        "cuisine": "Thai",
        "diet": "Non-Vegetarian",
        "time": "30 minutes",
        "calories": 210,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
        "pantry_match": 65,
        "ingredients": {"available": ["Shrimp", "Mushrooms", "Lemongrass", "Lime Juice"], "missing": ["Galangal", "Kaffir Lime Leaves", "Nam Prik Pao"]},
        "nutrition": {"protein": 18, "carbs": 12, "fat": 6, "fiber": 2},
        "health_benefits": ["Immune boosting", "Low calorie", "Anti-inflammatory"],
        "steps": [
            "Bring chicken broth to a boil in a medium pot",
            "Add lemongrass (bruised), galangal slices, and kaffir lime leaves",
            "Simmer for 5 minutes to infuse the broth",
            "Add mushrooms and shrimp, cook for 3 minutes",
            "Stir in fish sauce, lime juice, and chili paste (Nam Prik Pao)",
            "Taste and adjust seasoning — it should be sour, salty, and spicy",
            "Ladle into bowls and garnish with fresh cilantro and chili slices",
        ],
        "cultural": "Tom Yum is Thailand's national soup, recognized as one of the world's most flavorful broths.",
        "similar_dishes": ["Tom Kha Gai", "Pho", "Hot and Sour Soup"],
        "food_labels": ["soup", "tom yum", "thai soup", "shrimp soup", "spicy soup", "asian soup"],
    },
    {
        "id": 11,
        "title": "Idli Sambar",
        "cuisine": "Indian",
        "diet": "Vegan",
        "time": "40 minutes",
        "calories": 290,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Idli_Sambar.JPG/330px-Idli_Sambar.JPG",
        "pantry_match": 88,
        "ingredients": {"available": ["Idli Rice", "Urad Dal", "Toor Dal", "Tamarind", "Vegetables"], "missing": ["Sambar Powder"]},
        "nutrition": {"protein": 10, "carbs": 48, "fat": 4, "fiber": 8},
        "health_benefits": ["Probiotics from fermentation", "High fiber", "Low fat", "Good digestion"],
        "steps": [
            "Soak idli rice and urad dal separately for 6 hours",
            "Grind urad dal to a fluffy batter, then grind rice coarsely",
            "Combine batters with salt and ferment overnight",
            "Steam idlis in a greased idli mold for 10-12 minutes",
            "Pressure cook toor dal until soft",
            "Fry mustard seeds, curry leaves, and onions for the sambar base",
            "Add tamarind water, vegetables, and sambar powder",
            "Simmer with cooked dal for 15 minutes",
            "Serve hot idlis with sambar and coconut chutney",
        ],
        "cultural": "Idli Sambar is the quintessential South Indian breakfast enjoyed across Tamil Nadu and Karnataka.",
        "similar_dishes": ["Masala Dosa", "Uttapam", "Vada Sambar"],
        "food_labels": ["idli", "sambar", "south indian food", "steamed cake", "rice cake", "indian breakfast"],
    },
    {
        "id": 12,
        "title": "Spaghetti Carbonara",
        "cuisine": "Italian",
        "diet": "Non-Vegetarian",
        "time": "25 minutes",
        "calories": 620,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80",
        "pantry_match": 76,
        "ingredients": {"available": ["Spaghetti", "Eggs", "Parmesan", "Black Pepper"], "missing": ["Guanciale", "Pecorino Romano"]},
        "nutrition": {"protein": 26, "carbs": 68, "fat": 24, "fiber": 3},
        "health_benefits": ["High protein", "Calcium rich", "Energy rich"],
        "steps": [
            "Cook spaghetti in heavily salted boiling water until al dente",
            "Fry guanciale (or pancetta) in a pan until crispy, no oil needed",
            "Whisk eggs, grated Pecorino, grated Parmesan, and black pepper in a bowl",
            "Reserve 1 cup of starchy pasta cooking water",
            "Remove guanciale pan from heat, add drained spaghetti and toss",
            "Pour egg mixture over pasta and toss rapidly, adding pasta water little by little",
            "The heat from the pasta gently cooks the eggs into a creamy sauce",
            "Serve immediately with extra Pecorino and cracked black pepper",
        ],
        "cultural": "Carbonara originates from Rome and relies on the technique of emulsifying eggs without scrambling them.",
        "similar_dishes": ["Pasta Alfredo", "Cacio e Pepe", "Pasta Amatriciana"],
        "food_labels": ["pasta", "spaghetti", "carbonara", "italian pasta", "noodles", "creamy pasta"],
    },
    {
        "id": 13,
        "title": "Mango Lassi",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "10 minutes",
        "calories": 220,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Salt_lassi.jpg/330px-Salt_lassi.jpg",
        "pantry_match": 90,
        "ingredients": {"available": ["Mango", "Yogurt", "Milk", "Sugar", "Cardamom"], "missing": []},
        "nutrition": {"protein": 6, "carbs": 40, "fat": 5, "fiber": 2},
        "health_benefits": ["Probiotic", "Vitamin C", "Bone health", "Cooling drink"],
        "steps": [
            "Peel and dice ripe Alphonso or Kesar mangoes",
            "Add mango pieces, thick yogurt, and cold milk to a blender",
            "Add sugar to taste and a pinch of cardamom powder",
            "Blend on high until completely smooth and frothy",
            "Taste and adjust sweetness or consistency with more milk",
            "Pour into chilled glasses over ice cubes",
            "Garnish with a mango slice and a sprinkle of cardamom",
        ],
        "cultural": "Mango Lassi is a beloved Indian beverage, especially popular during summer across North India.",
        "similar_dishes": ["Plain Lassi", "Strawberry Lassi", "Mango Shake"],
        "food_labels": ["lassi", "mango drink", "smoothie", "indian drink", "yogurt drink", "mango lassi"],
    },
    {
        "id": 14,
        "title": "Falafel Wrap",
        "cuisine": "Middle Eastern",
        "diet": "Vegan",
        "time": "35 minutes",
        "calories": 420,
        "difficulty": "Medium",
        "meal": "Lunch",
        "image": "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80",
        "pantry_match": 70,
        "ingredients": {"available": ["Chickpeas", "Parsley", "Cumin", "Pita Bread", "Tomato", "Lettuce"], "missing": ["Tahini", "Sumac"]},
        "nutrition": {"protein": 16, "carbs": 52, "fat": 14, "fiber": 9},
        "health_benefits": ["High fiber", "Plant protein", "Heart healthy", "Iron rich"],
        "steps": [
            "Soak dried chickpeas overnight — do NOT use canned",
            "Blend chickpeas with parsley, garlic, cumin, coriander, and salt into a coarse mixture",
            "Refrigerate mixture for 30 minutes, then form into small balls",
            "Deep fry falafels at 180°C until deep golden brown, about 3 minutes",
            "Mix tahini with lemon juice, garlic, and water into a smooth sauce",
            "Warm pita bread and spread tahini sauce on the inside",
            "Load with falafel, tomato, cucumber, lettuce, and pickled turnips",
            "Drizzle with extra tahini and wrap tightly",
        ],
        "cultural": "Falafel is a staple street food across Egypt, Lebanon, and Israel with thousands of years of history.",
        "similar_dishes": ["Hummus Pita", "Shawarma", "Sabich"],
        "food_labels": ["falafel", "wrap", "pita wrap", "middle eastern food", "chickpea fritter", "street food"],
    },
    {
        "id": 15,
        "title": "Banana Pancakes",
        "cuisine": "Western",
        "diet": "Vegetarian",
        "time": "20 minutes",
        "calories": 340,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&q=80",
        "pantry_match": 92,
        "ingredients": {"available": ["Banana", "Eggs", "Flour", "Milk", "Baking Powder", "Butter"], "missing": []},
        "nutrition": {"protein": 10, "carbs": 55, "fat": 10, "fiber": 4},
        "health_benefits": ["Energy rich", "Potassium boost", "Mood improvement", "Natural sugars"],
        "steps": [
            "Mash two ripe bananas in a large bowl until smooth",
            "Whisk in 2 eggs and 120ml milk",
            "Sift in 150g flour and 1 tsp baking powder, mix until just combined",
            "Do not overmix — a few lumps are fine",
            "Heat a non-stick pan over medium heat and add a small knob of butter",
            "Pour 3 tbsp of batter per pancake and cook until bubbles form on top",
            "Flip and cook for 1 more minute until golden",
            "Serve stacked with maple syrup, banana slices, and a dust of powdered sugar",
        ],
        "cultural": "Pancakes are enjoyed across cultures worldwide — this banana version is a modern healthy twist.",
        "similar_dishes": ["Regular Pancakes", "Waffles", "Crêpes"],
        "food_labels": ["pancake", "banana pancake", "breakfast", "crepe", "hotcake", "sweet pancake"],
    },
    {
        "id": 16,
        "title": "Dal Makhani",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "60 minutes",
        "calories": 430,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Punjabi_style_Dal_Makhani.jpg/330px-Punjabi_style_Dal_Makhani.jpg",
        "pantry_match": 74,
        "ingredients": {"available": ["Black Lentils", "Kidney Beans", "Butter", "Tomatoes", "Cream"], "missing": ["Kasuri Methi", "Charcoal for Dhungar"]},
        "nutrition": {"protein": 20, "carbs": 50, "fat": 16, "fiber": 14},
        "health_benefits": ["High protein", "High fiber", "Iron rich", "Heart healthy"],
        "steps": [
            "Soak black lentils (urad dal) and kidney beans overnight",
            "Pressure cook with water, salt, and a pinch of baking soda for 30 minutes",
            "In a separate pan, heat butter and sauté finely chopped onions until golden",
            "Add ginger-garlic paste and cook until raw smell disappears",
            "Stir in tomato puree, red chili powder, and garam masala",
            "Combine the cooked dal with the tomato gravy",
            "Simmer on low heat for 20-30 minutes, stirring occasionally",
            "Stir in fresh cream and kasuri methi",
            "Finish with a large knob of butter and serve with naan or rice",
        ],
        "cultural": "Dal Makhani was invented at Moti Mahal restaurant in Delhi in the 1950s by Kundan Lal Gujral.",
        "similar_dishes": ["Butter Chicken", "Rajma", "Dal Tadka"],
        "food_labels": ["dal", "lentil curry", "north indian food", "black dal", "indian curry", "dal makhani"],
    },
    {
        "id": 18,
        "title": "Payasam",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "35 minutes",
        "calories": 310,
        "difficulty": "Easy",
        "meal": "Dessert",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Kheer.jpg/330px-Kheer.jpg",
        "pantry_match": 88,
        "ingredients": {"available": ["Milk", "Rice", "Sugar", "Cardamom", "Cashews", "Raisins"], "missing": ["Saffron"]},
        "nutrition": {"protein": 7, "carbs": 55, "fat": 9, "fiber": 1},
        "health_benefits": ["Calcium rich", "Energy boost", "Mood booster", "Bone health"],
        "steps": [
            "Wash rice and soak for 15 minutes, then drain",
            "Bring full-fat milk to a boil in a heavy-bottomed pan",
            "Add soaked rice and stir continuously on medium heat",
            "Cook for 20-25 minutes until rice is completely soft and milk thickens",
            "Add sugar and stir until fully dissolved",
            "Mix in cardamom powder and a few strands of saffron soaked in warm milk",
            "In a small pan, fry cashews and raisins in ghee until golden",
            "Pour the fried cashews and raisins over the payasam",
            "Serve warm or chilled — both ways are delicious",
        ],
        "cultural": "Payasam (Kheer) is an ancient Indian dessert mentioned in the Mahabharata, prepared during festivals and celebrations.",
        "similar_dishes": ["Kheer", "Firni", "Rice Pudding"],
        "food_labels": ["payasam", "kheer", "rice pudding", "indian dessert", "sweet porridge", "milk dessert"],
    },
    {
        "id": 19,
        "title": "Gulab Jamun",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "45 minutes",
        "calories": 380,
        "difficulty": "Medium",
        "meal": "Dessert",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Bowl_of_Gulab_Jamuns.jpg/330px-Bowl_of_Gulab_Jamuns.jpg",
        "pantry_match": 80,
        "ingredients": {"available": ["Milk Powder", "Flour", "Ghee", "Sugar", "Cardamom"], "missing": ["Khoya", "Rose Water"]},
        "nutrition": {"protein": 5, "carbs": 60, "fat": 14, "fiber": 1},
        "health_benefits": ["Instant energy", "Mood booster", "Good for celebrations"],
        "steps": [
            "Mix milk powder, a little flour, a pinch of baking soda, and ghee into a soft dough",
            "Add just enough milk to bind — dough should be soft but not sticky",
            "Rest the dough for 10 minutes covered with a damp cloth",
            "Prepare sugar syrup: dissolve 2 cups sugar in 1 cup water, add cardamom and rose water",
            "Simmer syrup for 5 minutes and keep warm",
            "Roll dough into smooth balls with no cracks — about marble size",
            "Deep fry the balls in ghee or oil on low heat, stirring gently for even browning",
            "Fry until deep golden brown — this takes about 8-10 minutes",
            "Transfer hot gulab jamuns directly into warm sugar syrup",
            "Soak for at least 2 hours before serving — they will double in size",
        ],
        "cultural": "Gulab Jamun is derived from a Persian dish and has been enjoyed across India for over 500 years.",
        "similar_dishes": ["Rasgulla", "Jamun", "Pantua"],
        "food_labels": ["gulab jamun", "indian sweet", "sweet ball", "fried sweet", "dessert", "mithai"],
    },
    {
        "id": 20,
        "title": "Rasgulla",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "50 minutes",
        "calories": 180,
        "difficulty": "Hard",
        "meal": "Dessert",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Rasgulla.jpg/330px-Rasgulla.jpg",
        "pantry_match": 75,
        "ingredients": {"available": ["Full-fat Milk", "Lemon Juice", "Sugar", "Water"], "missing": ["Rose Water"]},
        "nutrition": {"protein": 6, "carbs": 30, "fat": 4, "fiber": 0},
        "health_benefits": ["Calcium rich", "Low fat dessert", "Protein source"],
        "steps": [
            "Boil full-fat milk, then add lemon juice to curdle it",
            "Strain the chenna (paneer curd) through a muslin cloth",
            "Wash the chenna under cold water to remove lemon sourness",
            "Squeeze out excess water — chenna should be moist but not wet",
            "Knead chenna for 8-10 minutes until smooth and soft like dough",
            "Roll into small smooth balls with no cracks",
            "Boil sugar and water into a light syrup in a wide pot",
            "Drop chenna balls into boiling syrup, cover and cook for 15 minutes on medium heat",
            "Balls will double in size — do not open the lid during cooking",
            "Let cool, add rose water, and refrigerate before serving",
        ],
        "cultural": "Rasgulla originated in Odisha and Bengal and is now one of India's most iconic desserts, with a geographical indication tag.",
        "similar_dishes": ["Rasmalai", "Cham Cham", "Gulab Jamun"],
        "food_labels": ["rasgulla", "indian sweet", "chhena sweet", "syrup sweet", "bengali sweet", "mithai"],
    },
    {
        "id": 21,
        "title": "Halwa",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 420,
        "difficulty": "Easy",
        "meal": "Dessert",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Orient_sweets_%28special_halva%29_Samarkand%2C_Siyab.jpg/330px-Orient_sweets_%28special_halva%29_Samarkand%2C_Siyab.jpg",
        "pantry_match": 85,
        "ingredients": {"available": ["Semolina", "Sugar", "Ghee", "Water", "Cardamom", "Cashews"], "missing": ["Saffron"]},
        "nutrition": {"protein": 5, "carbs": 65, "fat": 16, "fiber": 2},
        "health_benefits": ["Quick energy", "Warming food", "Iron from semolina"],
        "steps": [
            "Heat ghee in a heavy pan over medium flame",
            "Add cashews and fry until golden, then set aside",
            "Add semolina (rava) to the same ghee and roast on low heat",
            "Stir continuously until semolina turns golden and smells nutty — about 8 minutes",
            "Carefully pour in hot water (2 cups per 1 cup semolina) — it will splutter",
            "Stir quickly to prevent lumps from forming",
            "Add sugar and mix well until fully combined",
            "Cook on low heat, stirring until halwa leaves the sides of the pan",
            "Mix in cardamom powder and saffron milk",
            "Garnish with fried cashews and serve hot",
        ],
        "cultural": "Sooji Halwa is a sacred offering (prasad) in Hindu temples and is served at weddings and festivals across India.",
        "similar_dishes": ["Gajar Halwa", "Moong Dal Halwa", "Sheera"],
        "food_labels": ["halwa", "sooji halwa", "semolina dessert", "indian sweet", "sheera", "rava halwa"],
    },
    {
        "id": 22,
        "title": "Pani Puri",
        "cuisine": "Indian",
        "diet": "Vegan",
        "time": "30 minutes",
        "calories": 200,
        "difficulty": "Medium",
        "meal": "Snack",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Pani_Puri1.JPG/330px-Pani_Puri1.JPG",
        "pantry_match": 70,
        "ingredients": {"available": ["Semolina", "Boiled Potatoes", "Chickpeas", "Tamarind", "Mint"], "missing": ["Puri", "Black Salt"]},
        "nutrition": {"protein": 5, "carbs": 38, "fat": 6, "fiber": 5},
        "health_benefits": ["Low calorie snack", "Digestive boost from mint", "Probiotic from tamarind"],
        "steps": [
            "Mix semolina and a little flour with water into a stiff dough and rest for 20 minutes",
            "Roll very thin and cut into small circles",
            "Deep fry on medium heat, pressing gently so they puff up",
            "Drain and cool on paper towels",
            "Boil and mash potatoes with boiled chickpeas, chaat masala, and tamarind chutney",
            "Blend mint, coriander, green chili, ginger, lemon juice, and black salt for green water",
            "Make sweet water with tamarind pulp, jaggery, cumin, and black salt",
            "Just before serving, make a hole in each puri with your thumb",
            "Fill with potato mixture and dip into spicy or sweet water",
            "Eat immediately in one gulp!",
        ],
        "cultural": "Pani Puri is India's most beloved street food, known as Golgappa in the North and Phuchka in Bengal.",
        "similar_dishes": ["Bhel Puri", "Sev Puri", "Dahi Puri"],
        "food_labels": ["pani puri", "golgappa", "phuchka", "indian street food", "chaat", "crispy puri"],
    },
    {
        "id": 23,
        "title": "Butter Chicken",
        "cuisine": "North Indian",
        "diet": "Non-Vegetarian",
        "time": "50 minutes",
        "calories": 580,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Butter_Chicken_%26_Butter_Naan_-_Home_-_Chandigarh_-_India_-_0006.jpg/330px-Butter_Chicken_%26_Butter_Naan_-_Home_-_Chandigarh_-_India_-_0006.jpg",
        "pantry_match": 76,
        "ingredients": {"available": ["Chicken", "Butter", "Tomatoes", "Onion", "Cream", "Spices"], "missing": ["Kasuri Methi", "Tandoor Paste"]},
        "nutrition": {"protein": 34, "carbs": 20, "fat": 32, "fiber": 3},
        "health_benefits": ["High protein", "Vitamin A from tomatoes", "Immune boosting"],
        "steps": [
            "Marinate chicken in yogurt, ginger-garlic paste, and spices for at least 2 hours",
            "Grill or pan-fry marinated chicken until slightly charred",
            "In the same pan, melt butter and fry onions until golden",
            "Add ginger-garlic paste and cook until fragrant",
            "Blend in tomato puree and cook for 15 minutes until oil separates",
            "Add red chili powder, coriander powder, and garam masala",
            "Add the grilled chicken to the sauce and simmer for 10 minutes",
            "Stir in fresh cream and crushed kasuri methi",
            "Finish with a generous knob of cold butter swirled in at the end",
            "Serve with naan or steamed basmati rice",
        ],
        "cultural": "Butter Chicken (Murgh Makhani) was accidentally invented at Moti Mahal in Delhi in the 1950s.",
        "similar_dishes": ["Chicken Tikka Masala", "Dal Makhani", "Paneer Butter Masala"],
        "food_labels": ["butter chicken", "murgh makhani", "chicken curry", "indian chicken", "creamy curry", "north indian food"],
    },
    {
        "id": 24,
        "title": "Jalebi",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "60 minutes",
        "calories": 350,
        "difficulty": "Hard",
        "meal": "Dessert",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Basavanagudi_Kadalekai_Parishe_%282025%29_Bangalore_%2886%29.jpg/330px-Basavanagudi_Kadalekai_Parishe_%282025%29_Bangalore_%2886%29.jpg",
        "pantry_match": 72,
        "ingredients": {"available": ["Flour", "Yogurt", "Sugar", "Saffron", "Ghee"], "missing": ["Yeast", "Rose Water", "Piping Bag"]},
        "nutrition": {"protein": 3, "carbs": 65, "fat": 14, "fiber": 1},
        "health_benefits": ["Quick energy", "Mood booster", "Iron from saffron"],
        "steps": [
            "Mix flour, yogurt, a pinch of turmeric, and yeast with water into a smooth thin batter",
            "Let the batter ferment for 8-12 hours at room temperature",
            "Prepare sugar syrup: boil sugar and water with saffron and cardamom to one-string consistency",
            "Keep syrup warm on very low heat",
            "Fill a squeeze bottle or piping bag with the fermented batter",
            "Heat ghee or oil in a wide shallow pan",
            "Pipe concentric circles quickly into the hot oil to form jalebi shapes",
            "Fry on medium heat until golden and crispy on both sides",
            "Transfer immediately to warm sugar syrup and soak for 1-2 minutes",
            "Serve hot — the contrast of crispy outside and syrup inside is key",
        ],
        "cultural": "Jalebi is believed to have Persian origins (Zulbia) and has been a part of Indian festivals for centuries.",
        "similar_dishes": ["Imarti", "Funnel Cake", "Gulab Jamun"],
        "food_labels": ["jalebi", "indian sweet", "fried sweet", "coil sweet", "syrup sweet", "festival sweet"],
    },
    {
        "id": 25,
        "title": "Chole Bhature",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "45 minutes",
        "calories": 680,
        "difficulty": "Medium",
        "meal": "Breakfast",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chole_Bhature_from_Nagpur.JPG/330px-Chole_Bhature_from_Nagpur.JPG",
        "pantry_match": 72,
        "ingredients": {"available": ["Chickpeas", "Flour", "Onion", "Tomatoes", "Spices", "Oil"], "missing": ["Anardana (Pomegranate Powder)", "Kashmiri Red Chili"]},
        "nutrition": {"protein": 18, "carbs": 82, "fat": 26, "fiber": 12},
        "health_benefits": ["High protein", "High fiber", "Iron rich", "Plant-based protein"],
        "steps": [
            "Soak chickpeas overnight and pressure cook with tea bags (for dark color)",
            "Prepare the chole masala: fry onions, add tomatoes and all spices",
            "Mix in cooked chickpeas and simmer for 20 minutes",
            "Mash a few chickpeas against the pot to thicken the gravy",
            "For bhature: knead maida (flour) with yogurt, oil, salt into a soft dough",
            "Rest dough for 2 hours for the yogurt to activate",
            "Roll into oval discs about 5mm thick",
            "Deep fry in hot oil — the bhatura will puff up dramatically",
            "Drain and serve immediately with the hot chole",
            "Garnish with raw onion rings, green chili, and lemon wedge",
        ],
        "cultural": "Chole Bhature is a popular Punjabi breakfast and is a staple street food from Delhi's Chandni Chowk.",
        "similar_dishes": ["Chole Puri", "Rajma Chawal", "Dal Makhani"],
        "food_labels": ["chole bhature", "chickpea curry", "fried bread", "north indian food", "punjabi food", "street food"],
    },
    {
        "id": 26,
        "title": "Tiramisu",
        "cuisine": "Italian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 430,
        "difficulty": "Medium",
        "meal": "Dessert",
        "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80",
        "pantry_match": 74,
        "ingredients": {"available": ["Eggs", "Sugar", "Coffee", "Cocoa Powder"], "missing": ["Mascarpone Cheese", "Ladyfinger Biscuits", "Rum"]},
        "nutrition": {"protein": 8, "carbs": 42, "fat": 22, "fiber": 1},
        "health_benefits": ["Mood booster", "Antioxidants from coffee and cocoa", "Energy rich"],
        "steps": [
            "Separate egg yolks and whites into two clean bowls",
            "Whisk yolks with sugar until pale, thick, and doubled in volume",
            "Fold mascarpone cheese into the yolk mixture until smooth",
            "Beat egg whites to stiff peaks and gently fold into the mascarpone mixture",
            "Brew strong espresso and mix with a splash of rum or coffee liqueur, let cool",
            "Quickly dip ladyfinger biscuits one by one into the coffee mixture — 1 second per side",
            "Lay a layer of soaked ladyfingers in a deep dish",
            "Spread half the mascarpone cream over the biscuits",
            "Repeat with another layer of ladyfingers and remaining cream",
            "Dust generously with cocoa powder, refrigerate for at least 4 hours before serving",
        ],
        "cultural": "Tiramisu means 'pick me up' in Italian and originated in Treviso, Italy in the late 1960s.",
        "similar_dishes": ["Panna Cotta", "Charlotte Royale", "Chocolate Mousse"],
        "food_labels": ["tiramisu", "italian dessert", "coffee dessert", "mascarpone dessert", "no bake dessert", "layered dessert"],
    },
    {
        "id": 27,
        "title": "Aloo Paratha",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 410,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Triangle_paratha_%28cropped%29.JPG/330px-Triangle_paratha_%28cropped%29.JPG",
        "pantry_match": 90,
        "ingredients": {"available": ["Whole Wheat Flour", "Potatoes", "Onion", "Green Chili", "Spices", "Ghee"], "missing": []},
        "nutrition": {"protein": 9, "carbs": 60, "fat": 14, "fiber": 6},
        "health_benefits": ["High fiber", "Energy rich", "Good for digestion", "Iron from whole wheat"],
        "steps": [
            "Knead whole wheat flour with water and a pinch of salt into a soft smooth dough",
            "Rest dough covered for 20 minutes",
            "Boil potatoes until tender, peel and mash completely while hot",
            "Mix mashed potato with finely chopped onion, green chili, cumin seeds, and coriander",
            "Season with chaat masala, amchur (dry mango powder), and salt",
            "Divide dough into balls, flatten slightly, place a ball of filling in the center",
            "Gather dough edges around the filling and seal into a stuffed ball",
            "Gently roll out into a thick flatbread, being careful not to burst the filling",
            "Cook on a hot tawa (griddle) with generous ghee on both sides until golden spots appear",
            "Serve piping hot with yogurt, pickle, and white butter",
        ],
        "cultural": "Aloo Paratha is the pride of Punjabi breakfasts and is iconic at the dhabas (roadside eateries) of Amritsar.",
        "similar_dishes": ["Plain Paratha", "Gobhi Paratha", "Mooli Paratha"],
        "food_labels": ["paratha", "aloo paratha", "stuffed flatbread", "north indian breakfast", "punjabi food", "flatbread"],
    },
    {
        "id": 28,
        "title": "Pesarattu",
        "cuisine": "South Indian",
        "diet": "Vegan",
        "time": "25 minutes",
        "calories": 250,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Pesarattu.jpg/330px-Pesarattu.jpg",
        "pantry_match": 88,
        "ingredients": {"available": ["Green Gram", "Ginger", "Green Chili", "Cumin", "Onion"], "missing": ["Rice (optional)"]},
        "nutrition": {"protein": 14, "carbs": 30, "fat": 7, "fiber": 8},
        "health_benefits": ["High protein", "Low oil", "Gluten free"],
        "steps": [
            "Soak whole green gram for 5-6 hours and grind with ginger and chili.",
            "Add salt and cumin; keep batter slightly coarse.",
            "Spread thin on a hot tawa like dosa.",
            "Top with chopped onion and drizzle a little oil.",
            "Cook both sides and serve with ginger chutney.",
        ],
        "cultural": "Pesarattu is a traditional Andhra breakfast made from green gram.",
        "similar_dishes": ["Dosa", "Adai", "Moong Dal Chilla"],
        "food_labels": ["pesarattu", "green gram dosa", "breakfast", "south indian food"],
    },
    {
        "id": 29,
        "title": "Upma",
        "cuisine": "Indian",
        "diet": "Vegan",
        "time": "20 minutes",
        "calories": 240,
        "difficulty": "Easy",
        "meal": "Breakfast",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/A_photo_of_Upma.jpg/330px-A_photo_of_Upma.jpg",
        "pantry_match": 90,
        "ingredients": {"available": ["Semolina", "Onion", "Green Chili", "Curry Leaves", "Mustard Seeds"], "missing": ["Cashews"]},
        "nutrition": {"protein": 6, "carbs": 36, "fat": 7, "fiber": 3},
        "health_benefits": ["Light meal", "Quick breakfast", "Comfort food"],
        "steps": [
            "Dry roast semolina lightly and keep aside.",
            "Temper mustard seeds, curry leaves, onion, and chili in oil.",
            "Add hot water and salt, then simmer.",
            "Slowly add semolina while stirring continuously.",
            "Cook until fluffy and serve hot.",
        ],
        "cultural": "Upma is a classic South Indian breakfast prepared in many Indian homes.",
        "similar_dishes": ["Poha", "Sheera", "Pongal"],
        "food_labels": ["upma", "semolina", "breakfast", "indian food"],
    },
    {
        "id": 30,
        "title": "Rajma Chawal",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "50 minutes",
        "calories": 460,
        "difficulty": "Medium",
        "meal": "Lunch",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Rajma_Masala_%2832081557778%29.jpg/330px-Rajma_Masala_%2832081557778%29.jpg",
        "pantry_match": 84,
        "ingredients": {"available": ["Kidney Beans", "Rice", "Onion", "Tomato", "Garlic", "Spices"], "missing": ["Kasuri Methi"]},
        "nutrition": {"protein": 15, "carbs": 62, "fat": 10, "fiber": 12},
        "health_benefits": ["Plant protein", "High fiber", "Iron rich"],
        "steps": [
            "Soak rajma overnight and pressure cook until soft.",
            "Saute onion, ginger, garlic, and tomato puree with spices.",
            "Add cooked rajma and simmer until thick.",
            "Cook basmati rice separately.",
            "Serve hot rajma over steamed rice.",
        ],
        "cultural": "Rajma chawal is a comfort lunch staple across North India.",
        "similar_dishes": ["Chole Chawal", "Dal Chawal", "Lobia Curry"],
        "food_labels": ["rajma", "kidney beans", "rice", "lunch", "indian curry"],
    },
    {
        "id": 31,
        "title": "Chana Masala",
        "cuisine": "North Indian",
        "diet": "Non-Vegetarian",
        "time": "40 minutes",
        "calories": 360,
        "difficulty": "Medium",
        "meal": "Lunch",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Chana_masala.jpg/330px-Chana_masala.jpg",
        "pantry_match": 86,
        "ingredients": {"available": ["Chickpeas", "Onion", "Tomato", "Garlic", "Ginger", "Spices"], "missing": ["Anardana Powder"]},
        "nutrition": {"protein": 14, "carbs": 42, "fat": 11, "fiber": 11},
        "health_benefits": ["Plant protein", "High fiber", "Iron rich"],
        "steps": [
            "Pressure cook soaked chickpeas until soft.",
            "Saute onion, ginger, garlic, and tomato with spices.",
            "Add cooked chickpeas and simmer until thick.",
            "Adjust tang with amchur or lemon juice.",
            "Serve with rice or roti.",
        ],
        "cultural": "Chana Masala is a staple Punjabi curry enjoyed across India.",
        "similar_dishes": ["Rajma", "Chole Bhature", "Pindi Chana"],
        "food_labels": ["chana masala", "chickpea curry", "lunch", "indian curry"],
    },
    {
        "id": 32,
        "title": "Palak Paneer",
        "cuisine": "North Indian",
        "diet": "Vegetarian",
        "time": "40 minutes",
        "calories": 390,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Palakpaneer_Rayagada_Odisha_0009.jpg/330px-Palakpaneer_Rayagada_Odisha_0009.jpg",
        "pantry_match": 82,
        "ingredients": {"available": ["Spinach", "Paneer", "Onion", "Tomato", "Garlic", "Spices"], "missing": ["Cream"]},
        "nutrition": {"protein": 21, "carbs": 18, "fat": 24, "fiber": 7},
        "health_benefits": ["Calcium rich", "Iron rich", "High protein"],
        "steps": [
            "Blanch spinach and blend into a smooth puree.",
            "Saute onion, garlic, and tomato with spices.",
            "Add spinach puree and simmer for 6-8 minutes.",
            "Add paneer cubes and cook for 4 minutes.",
            "Serve with roti or jeera rice.",
        ],
        "cultural": "Palak paneer is a classic Punjabi curry loved for flavor and nutrition.",
        "similar_dishes": ["Saag Paneer", "Matar Paneer", "Shahi Paneer"],
        "food_labels": ["palak paneer", "spinach curry", "paneer", "dinner", "indian curry"],
    },
    {
        "id": 33,
        "title": "Rogan Josh",
        "cuisine": "Kashmiri",
        "diet": "Non-Vegetarian",
        "time": "55 minutes",
        "calories": 520,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Rogan_Josh_Kashmiri.jpg/330px-Rogan_Josh_Kashmiri.jpg",
        "pantry_match": 75,
        "ingredients": {"available": ["Mutton", "Onion", "Yogurt", "Kashmiri Chili", "Whole Spices"], "missing": ["Saffron"]},
        "nutrition": {"protein": 30, "carbs": 10, "fat": 34, "fiber": 2},
        "health_benefits": ["High protein", "Iron rich", "Energy dense"],
        "steps": [
            "Marinate mutton with yogurt and spices.",
            "Brown onions and whole spices in mustard oil.",
            "Add marinated mutton and sear well.",
            "Add water and slow cook until tender.",
            "Finish with saffron and serve with rice.",
        ],
        "cultural": "Rogan Josh is a signature Kashmiri curry introduced during Mughal influence.",
        "similar_dishes": ["Laal Maas", "Mutton Curry", "Yakhni"],
        "food_labels": ["rogan josh", "mutton curry", "kashmiri food", "dinner"],
    },
    {
        "id": 34,
        "title": "Roasted Chickpea Chaat",
        "cuisine": "Indian",
        "diet": "Vegan",
        "time": "15 minutes",
        "calories": 210,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Dahi_puri%2C_Doi_phuchka.jpg/330px-Dahi_puri%2C_Doi_phuchka.jpg",
        "pantry_match": 92,
        "ingredients": {"available": ["Boiled Chickpeas", "Onion", "Tomato", "Cucumber", "Lemon", "Chaat Masala"], "missing": []},
        "nutrition": {"protein": 10, "carbs": 26, "fat": 6, "fiber": 8},
        "health_benefits": ["High fiber", "Protein snack", "Low calorie"],
        "steps": [
            "Roast chickpeas with little oil and spices until crisp.",
            "Mix chopped onion, tomato, and cucumber in a bowl.",
            "Add roasted chickpeas and toss with lemon juice.",
            "Season with chaat masala and salt.",
            "Serve immediately.",
        ],
        "cultural": "Chaat style snacks are popular evening foods across India.",
        "similar_dishes": ["Bhel Puri", "Sprout Salad", "Masala Corn"],
        "food_labels": ["chickpea", "chaat", "snack", "high fiber", "indian food"],
    },
    {
        "id": 35,
        "title": "Rasmalai",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "35 minutes",
        "calories": 280,
        "difficulty": "Easy",
        "meal": "Dessert",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Ras_Malai_2.JPG/330px-Ras_Malai_2.JPG",
        "pantry_match": 88,
        "ingredients": {"available": ["Milk", "Lemon Juice", "Sugar", "Cardamom", "Saffron"], "missing": ["Pistachios"]},
        "nutrition": {"protein": 9, "carbs": 30, "fat": 11, "fiber": 1},
        "health_benefits": ["Calcium rich", "Festive dessert", "Protein source"],
        "steps": [
            "Prepare fresh chenna from milk and shape into small discs.",
            "Cook discs in light sugar syrup until soft.",
            "Reduce milk with sugar, cardamom, and saffron to make rabri.",
            "Soak chenna discs in chilled rabri.",
            "Garnish with nuts and serve cold.",
        ],
        "cultural": "Rasmalai is a popular Bengali and North Indian festive sweet.",
        "similar_dishes": ["Rasgulla", "Kheer", "Rabri"],
        "food_labels": ["rasmalai", "indian dessert", "milk sweet", "mithai"],
    },
    {
        "id": 36,
        "title": "Samosa",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "40 minutes",
        "calories": 300,
        "difficulty": "Medium",
        "meal": "Snack",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Samosa-and-Chatni.jpg/330px-Samosa-and-Chatni.jpg",
        "pantry_match": 86,
        "ingredients": {"available": ["Flour", "Potato", "Peas", "Cumin", "Coriander", "Oil"], "missing": ["Ajwain"]},
        "nutrition": {"protein": 6, "carbs": 38, "fat": 14, "fiber": 4},
        "health_benefits": ["Energy rich", "Popular tea-time snack"],
        "steps": [
            "Prepare dough with flour, salt, and oil.",
            "Cook potato-pea filling with spices.",
            "Shape samosas and seal edges.",
            "Deep fry on medium-low heat until crisp.",
            "Serve with chutney.",
        ],
        "cultural": "Samosa is one of India's most iconic street snacks.",
        "similar_dishes": ["Kachori", "Pakora", "Aloo Tikki"],
        "food_labels": ["samosa", "snack", "street food", "indian food"],
    },
    {
        "id": 37,
        "title": "Vada Pav",
        "cuisine": "Maharashtrian",
        "diet": "Vegetarian",
        "time": "25 minutes",
        "calories": 330,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Vada_Pav-Indian_street_food.JPG/330px-Vada_Pav-Indian_street_food.JPG",
        "pantry_match": 90,
        "ingredients": {"available": ["Potato", "Pav Bun", "Gram Flour", "Garlic Chutney", "Green Chili"], "missing": []},
        "nutrition": {"protein": 7, "carbs": 45, "fat": 12, "fiber": 4},
        "health_benefits": ["Quick snack", "Affordable meal"],
        "steps": [
            "Make spiced mashed potato balls.",
            "Dip in gram flour batter and deep fry.",
            "Slice pav and spread chutneys.",
            "Place vada inside pav and serve hot.",
        ],
        "cultural": "Vada Pav is Mumbai's most famous street food.",
        "similar_dishes": ["Dabeli", "Samosa Pav", "Misal Pav"],
        "food_labels": ["vada pav", "mumbai street food", "snack"],
    },
    {
        "id": 38,
        "title": "Pav Bhaji",
        "cuisine": "Maharashtrian",
        "diet": "Vegetarian",
        "time": "35 minutes",
        "calories": 390,
        "difficulty": "Easy",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Bambayya_Pav_bhaji.jpg/330px-Bambayya_Pav_bhaji.jpg",
        "pantry_match": 84,
        "ingredients": {"available": ["Potato", "Tomato", "Capsicum", "Peas", "Butter", "Pav"], "missing": ["Pav Bhaji Masala"]},
        "nutrition": {"protein": 9, "carbs": 44, "fat": 19, "fiber": 7},
        "health_benefits": ["Vegetable rich", "Comfort food"],
        "steps": [
            "Boil and mash mixed vegetables.",
            "Saute onions and tomatoes with pav bhaji masala.",
            "Add mashed vegetables and butter, simmer well.",
            "Toast pav with butter on griddle.",
            "Serve with lemon and onion.",
        ],
        "cultural": "Pav Bhaji originated as a mill-worker meal in Mumbai.",
        "similar_dishes": ["Bhaji Pav", "Masala Pav", "Misal Pav"],
        "food_labels": ["pav bhaji", "indian street food", "dinner"],
    },
    {
        "id": 39,
        "title": "Dhokla",
        "cuisine": "Gujarati",
        "diet": "Vegetarian",
        "time": "30 minutes",
        "calories": 190,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Dhokla_on_Gujrart.jpg/330px-Dhokla_on_Gujrart.jpg",
        "pantry_match": 91,
        "ingredients": {"available": ["Gram Flour", "Yogurt", "Eno", "Mustard Seeds", "Curry Leaves"], "missing": []},
        "nutrition": {"protein": 8, "carbs": 22, "fat": 6, "fiber": 3},
        "health_benefits": ["Light snack", "Fermented food", "Protein source"],
        "steps": [
            "Mix gram flour, yogurt, and spices into smooth batter.",
            "Add fruit salt and steam immediately.",
            "Prepare tempering with mustard seeds and curry leaves.",
            "Pour tempering over dhokla and cut into pieces.",
            "Serve with green chutney.",
        ],
        "cultural": "Dhokla is a famous Gujarati steamed snack.",
        "similar_dishes": ["Khaman", "Handvo", "Patra"],
        "food_labels": ["dhokla", "gujarati snack", "steamed snack"],
    },
    {
        "id": 40,
        "title": "Aloo Tikki",
        "cuisine": "Indian",
        "diet": "Vegetarian",
        "time": "25 minutes",
        "calories": 240,
        "difficulty": "Easy",
        "meal": "Snack",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Aloo_Tikki_served_with_chutneys.jpg/330px-Aloo_Tikki_served_with_chutneys.jpg",
        "pantry_match": 89,
        "ingredients": {"available": ["Potato", "Green Peas", "Breadcrumbs", "Spices", "Oil"], "missing": ["Cornflour"]},
        "nutrition": {"protein": 5, "carbs": 32, "fat": 9, "fiber": 4},
        "health_benefits": ["Filling snack", "Carb energy"],
        "steps": [
            "Boil potatoes and mash with spices.",
            "Shape patties and coat lightly with crumbs.",
            "Shallow fry until golden on both sides.",
            "Serve with mint and tamarind chutney.",
        ],
        "cultural": "Aloo Tikki is a popular North Indian chaat base.",
        "similar_dishes": ["Cutlet", "Hara Bhara Kabab", "Samosa"],
        "food_labels": ["aloo tikki", "chaat", "snack", "indian food"],
    },
    {
        "id": 41,
        "title": "Kung Pao Chicken",
        "cuisine": "Chinese",
        "diet": "Non-Vegetarian",
        "time": "30 minutes",
        "calories": 420,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Kung-pao-shanghai.jpg/330px-Kung-pao-shanghai.jpg",
        "pantry_match": 78,
        "ingredients": {"available": ["Chicken", "Peanuts", "Soy Sauce", "Dried Chili", "Garlic", "Ginger"], "missing": ["Sichuan Peppercorn"]},
        "nutrition": {"protein": 29, "carbs": 16, "fat": 23, "fiber": 3},
        "health_benefits": ["High protein", "Rich flavor", "Quick stir-fry meal"],
        "steps": [
            "Marinate diced chicken in soy sauce and cornstarch.",
            "Stir-fry chicken until nearly cooked and set aside.",
            "Saute garlic, ginger, dried chilies, and peppercorns.",
            "Add sauce and toss chicken with peanuts.",
            "Serve hot with steamed rice.",
        ],
        "cultural": "Kung Pao Chicken is a famous Sichuan dish known for spicy and nutty flavors.",
        "similar_dishes": ["General Tso's Chicken", "Szechuan Chicken", "Chili Chicken"],
        "food_labels": ["kung pao", "chicken", "chinese food", "stir fry"],
    },
    {
        "id": 42,
        "title": "Sushi Platter",
        "cuisine": "Japanese",
        "diet": "Non-Vegetarian",
        "time": "45 minutes",
        "calories": 360,
        "difficulty": "Hard",
        "meal": "Lunch",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/330px-Sushi_platter.jpg",
        "pantry_match": 70,
        "ingredients": {"available": ["Sushi Rice", "Nori", "Salmon", "Cucumber", "Vinegar"], "missing": ["Wasabi", "Pickled Ginger"]},
        "nutrition": {"protein": 18, "carbs": 45, "fat": 10, "fiber": 3},
        "health_benefits": ["Lean protein", "Omega-3", "Balanced meal"],
        "steps": [
            "Cook sushi rice and season with rice vinegar.",
            "Prepare fish and vegetables into strips.",
            "Place rice on nori and add fillings.",
            "Roll tightly and slice into pieces.",
            "Serve with soy sauce, wasabi, and ginger.",
        ],
        "cultural": "Sushi is one of Japan's most iconic dishes, emphasizing freshness and precision.",
        "similar_dishes": ["Maki", "Nigiri", "Sashimi"],
        "food_labels": ["sushi", "japanese food", "rice roll", "seafood"],
    },
    {
        "id": 43,
        "title": "Bibimbap",
        "cuisine": "Korean",
        "diet": "Non-Vegetarian",
        "time": "35 minutes",
        "calories": 490,
        "difficulty": "Medium",
        "meal": "Lunch",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/330px-Dolsot-bibimbap.jpg",
        "pantry_match": 75,
        "ingredients": {"available": ["Rice", "Beef", "Spinach", "Carrot", "Mushroom", "Egg"], "missing": ["Gochujang"]},
        "nutrition": {"protein": 24, "carbs": 54, "fat": 16, "fiber": 6},
        "health_benefits": ["Balanced macros", "Vegetable rich", "High satiety"],
        "steps": [
            "Cook rice and prepare vegetables separately.",
            "Saute beef with soy and sesame oil.",
            "Arrange rice, vegetables, and beef in a bowl.",
            "Top with fried egg and gochujang.",
            "Mix well before eating.",
        ],
        "cultural": "Bibimbap is a classic Korean mixed-rice dish with colorful toppings.",
        "similar_dishes": ["Japchae", "Kimbap", "Bulgogi Bowl"],
        "food_labels": ["bibimbap", "korean food", "rice bowl", "mixed rice"],
    },
    {
        "id": 44,
        "title": "Paella Valenciana",
        "cuisine": "Mediterranean",
        "diet": "Non-Vegetarian",
        "time": "50 minutes",
        "calories": 540,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/01_Paella_Valenciana_original.jpg/330px-01_Paella_Valenciana_original.jpg",
        "pantry_match": 68,
        "ingredients": {"available": ["Rice", "Chicken", "Seafood", "Saffron", "Bell Pepper", "Peas"], "missing": ["Paella Pan"]},
        "nutrition": {"protein": 27, "carbs": 56, "fat": 18, "fiber": 5},
        "health_benefits": ["Protein rich", "Seafood nutrients", "One-pan meal"],
        "steps": [
            "Saute chicken and aromatics in olive oil.",
            "Add rice, saffron stock, and vegetables.",
            "Arrange seafood on top and simmer uncovered.",
            "Cook until rice is tender and socarrat forms.",
            "Rest briefly and serve with lemon wedges.",
        ],
        "cultural": "Paella is a celebrated Mediterranean rice dish from Valencia, Spain.",
        "similar_dishes": ["Seafood Risotto", "Jambalaya", "Pilaf"],
        "food_labels": ["paella", "mediterranean food", "rice", "seafood"],
    },
    {
        "id": 45,
        "title": "Chicken Gyros",
        "cuisine": "Greek",
        "diet": "Non-Vegetarian",
        "time": "30 minutes",
        "calories": 430,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pita_giros.JPG/330px-Pita_giros.JPG",
        "pantry_match": 79,
        "ingredients": {"available": ["Chicken", "Pita", "Tomato", "Onion", "Yogurt", "Cucumber"], "missing": ["Dill"]},
        "nutrition": {"protein": 26, "carbs": 36, "fat": 17, "fiber": 4},
        "health_benefits": ["High protein", "Fresh toppings", "Balanced meal"],
        "steps": [
            "Marinate chicken in yogurt, lemon, and herbs.",
            "Grill or pan-sear until cooked and slice thin.",
            "Prepare tzatziki with yogurt, cucumber, and garlic.",
            "Warm pita and fill with chicken and vegetables.",
            "Serve wrapped with extra tzatziki.",
        ],
        "cultural": "Gyros are a staple Greek street food served in pita with tzatziki.",
        "similar_dishes": ["Shawarma", "Doner Kebab", "Souvlaki"],
        "food_labels": ["gyros", "greek food", "pita", "chicken wrap"],
    },
    {
        "id": 46,
        "title": "Ratatouille",
        "cuisine": "French",
        "diet": "Vegan",
        "time": "40 minutes",
        "calories": 260,
        "difficulty": "Medium",
        "meal": "Dinner",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Ratatouille_home_cooked.jpg/330px-Ratatouille_home_cooked.jpg",
        "pantry_match": 85,
        "ingredients": {"available": ["Eggplant", "Zucchini", "Tomato", "Bell Pepper", "Garlic", "Olive Oil"], "missing": ["Fresh Thyme"]},
        "nutrition": {"protein": 6, "carbs": 24, "fat": 14, "fiber": 9},
        "health_benefits": ["High fiber", "Antioxidants", "Low calorie"],
        "steps": [
            "Slice vegetables evenly and season.",
            "Prepare tomato-garlic base in a baking dish.",
            "Layer vegetables in spiral pattern.",
            "Bake until tender and lightly caramelized.",
            "Serve warm with bread or rice.",
        ],
        "cultural": "Ratatouille is a classic Provençal vegetable stew from France.",
        "similar_dishes": ["Tian", "Ratatouille Nicoise", "Vegetable Gratin"],
        "food_labels": ["ratatouille", "french food", "vegetable stew", "vegan"],
    },
    {
        "id": 47,
        "title": "Classic Hamburger",
        "cuisine": "American",
        "diet": "Non-Vegetarian",
        "time": "20 minutes",
        "calories": 610,
        "difficulty": "Easy",
        "meal": "Lunch",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/RedDot_Burger.jpg/330px-RedDot_Burger.jpg",
        "pantry_match": 82,
        "ingredients": {"available": ["Beef Patty", "Burger Bun", "Lettuce", "Tomato", "Cheese", "Onion"], "missing": ["Pickles"]},
        "nutrition": {"protein": 32, "carbs": 39, "fat": 34, "fiber": 3},
        "health_benefits": ["Protein dense", "Energy rich"],
        "steps": [
            "Season and shape ground beef into patties.",
            "Grill patties to desired doneness.",
            "Toast buns lightly with butter.",
            "Assemble with cheese, lettuce, tomato, and onion.",
            "Serve with a side salad or fries.",
        ],
        "cultural": "Hamburger is one of the most iconic American fast-casual foods.",
        "similar_dishes": ["Cheeseburger", "Chicken Burger", "Sliders"],
        "food_labels": ["hamburger", "american food", "burger", "beef"],
    },
]


def seed():
    db = SessionLocal()
    try:
        is_postgres = engine.dialect.name == "postgresql"
        existing_recipes = {r.id: r for r in db.query(Recipe).all()}
        inserted_count = 0
        updated_count = 0

        for data in RECIPES:
            existing = existing_recipes.get(data["id"])
            if existing:
                updated_count += 1
                for key, value in data.items():
                    if key != "id":
                        setattr(existing, key, value)
            else:
                db.add(Recipe(**data))
                inserted_count += 1

        # Remove deprecated recipes that should no longer appear in the app.
        removed_count = db.query(Recipe).filter(Recipe.title == "Avocado Toast").delete(synchronize_session=False)

        db.commit()

        # Reset only for PostgreSQL so future auto-increment IDs don't collide
        # with the manually-seeded IDs (0–27).
        if is_postgres:
            db.execute(text("SELECT setval('recipes_id_seq', (SELECT MAX(id) FROM recipes) + 1, false)"))
            db.commit()

        total = db.query(Recipe).count()
        print(f"✅ Inserted: {inserted_count}, Updated: {updated_count}, Removed: {removed_count}, Total in DB: {total}")
        if is_postgres:
            print(f"✅ PostgreSQL sequence reset to {total + 1}")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
